### ISSUE TITLE
5.1.9 fails due absence of redux-logger

### ISSUE THREAD

**Issue by algbeta** [bencripps/react-redux-grid#102]
Hi!
I've tried to install a new version of react-redux-grid but it fails due absence of redux-logger.
I installed it manually in node_modules/react-redux-grid and that fixed the problem.
I'm not totally sure but there might be a problem with published package.

**Comment by bencripps** [comment]
This is a bug in the newest release as grid. The logger is listed as a `dev-dependency` -- even though it's only used in the dev store, it's still being required.

I will make this change and push a new release.
