### ISSUE TITLE
Question: 5.1.2 switch react context causes problems

### ISSUE THREAD

**Issue by algbeta** [bencripps/react-redux-grid#103]
Hi Ben!

I'm struggling with a very odd issues.
I've tried to switch to 5.1.9 from 5.1.0 but since 5.1.2 my grid is always empty.

It's definitely about getting store from the context bc when i change 
```
    getStore = () => this.context.store || this.props.store
```
to 
```
    getStore = () => this.props.store
```

Everything works fine
The weird thing that both stores from context and from props seems to be completely valid but if the one from the context is taken no actions are caught in reducers...

Do you have any thoughts about that?
Thanks a lot!

**Comment by bencripps** [comment]
It sounds like you're importing two stores into your app (perhaps one from Grid, and one for your own app).

Here's some documentation: http://redux.js.org/docs/api/Store.html but you should only be importing a single store. Let me know if this helps.

**Comment by algbeta** [comment]
Hi Ben!
I guessed the same. 
I import one store from node_modules/ and one more from the node_modules/react-redux-grid/node-modules/

On gitter I also proposed to move react/redux/react-redux/react-dom/(immutablejs?) to dev dependencies or peer dependencies? It will exclude that problem + lighten the weight of react-redux-grid dist.
What do you think?

**Comment by bencripps** [comment]
Hmm -- `immutablejs` is a dependency for grid -- as it uses immutable data structures internally, `react-dom` is also a hard requirement.

You shouldn't be importing the `store` at all. I think if you stop using that store, your problem should resolve.

**Comment by algbeta** [comment]
I've checked the code. Now i'm sure that I  import only single store I created myself but i still see the problem present. Could it be bc of the instance taken from context by default is not the one I try to pass?

**Comment by bencripps** [comment]
Hmm, I don't think so. The contextual store should be whatever store is being used. I have the grid pulling a different store than the default one in a couple other apps, so I know it works. 

Would you mind putting together the smallest version of your app, so I could debug it and see what's going on?

**Comment by algbeta** [comment]
Hi again!
I've solved both problems.
I had one with configuration.
I fixed duplicate packages problem during bundle optimization process so I don't have any questions/suggestions according to this issue.

Thank you very much!
Please, close the issue.
