### ISSUE TITLE
Is it posible to skip/override default styles applied in JS?

### ISSUE THREAD

**Issue by algbeta** [bencripps/react-redux-grid#110]
Hi Ben!
Thank you very much for a great work!

Skipping inline css made my life a lot easier. 
But there is a thing I don't find pretty.
When there is a grid with only one row it still has default 500px height.
Is it possible to exclude those default styles applied with js too?
I created my own styles and would like to rely on them.

Is  that possible?
Thank you!

**Comment by bencripps** [comment]
Sure thing. When you instantiate grid now, if you provide `height: false`, no height will be set.

```js
import { Grid } from 'react-redux-grid';

<Grid height={false} />
```

**Comment by algbeta** [comment]
@bencripps and what about other styles? with `height={false}` i have problems displaying edit dialog in `mode=inline`

**Comment by bencripps** [comment]
Hmm, not sure what you mean. With `height: false` the inline editor works in the demo. Can you try in the demo?

**Comment by algbeta** [comment]
I meant that Save/Cancel buttons are hidden in inline edit mode.
I've run your demo with one item. What I see when try to edit an item:
![screenshot 27 _edited](https://cloud.githubusercontent.com/assets/3833520/23071748/6bdec270-f540-11e6-9ae4-0d5afee26bc6.jpg)

It happens bc of top property for .react-grid-inline-editor  which is set in JS and overflow applied in .react-grid-table-container.
Since I applied my own styles, I can change overflow easily but I'm not willing to change top prop

**Comment by bencripps** [comment]
Yeah, this happens when there's only a single row. If you had more rows this wouldn't be an issue. We can't change the `overflow: hidden` for the grid-container since that's what makes it scrollable.

**Comment by algbeta** [comment]
All right but the question is : is that possible to override top property for editor container (or any other property set in JS) in easy way?

**Comment by bencripps** [comment]
Since the top is set dynamically via JS, the only way would be to override it with an `!important` in your specific CSS.

**Comment by algbeta** [comment]
Hi again. Thank you for clarification. I will use `!important` to fix styles locally on my project so it's up to you to add changes to editor styles.

Best regards!
