### ISSUE TITLE
Question: render row in different color

### ISSUE THREAD

**Issue by darlenya** [bencripps/react-redux-grid#111]
Hi,

I would like to render a row in different colors depending on values in the row. I tried this with a custom columnRenderer but then the spaces between the cells do not have the color. Is there a way to do this?

**Comment by headwinds** [comment]
If you set your rows (tr) background to transparent with css, you could achieve that effect using a custom cell (td). Each cell in the row would have the same color value. Yes custom columnRenderer is the right example to follow.

**Comment by bencripps** [comment]
Give that a try -- sounds like a good approach to me.

**Comment by darlenya** [comment]
I will try that and report if it is working. Thanks

**Comment by headwinds** [comment]
I think what we really want is a row renderer though where we could set the cell renderer -either custom or default for each cell - and have the ability to set a custom style for the entire row (the tr)

**Comment by darlenya** [comment]
I try around since a few hours. Your first suggestion is not working as I need it. 
Currently I try to write a row renderer. But I am still a little bit confused how to do it. I think it could be possible to just replace the "rowEl = (<tr { ...rowProps }> { cells } </tr>);" in the Row.jsx with a function which could be provided like it is done with the column renderer.

**Comment by headwinds** [comment]
What if you created a row-renderer branch and then we can review your work - sounds like you have a solid idea

**Comment by darlenya** [comment]
I just startet this. And will create a pull request

**Comment by darlenya** [comment]
The pull request is there, so I will close this issue
