### ISSUE TITLE
Document update - pass rowId to update cell value

### ISSUE THREAD

**Issue by sanketmeghani** [bencripps/react-redux-grid#117]
I was trying to use a custom editor and followed the document available [USING_CUSTOM_EDITORS](https://github.com/bencripps/react-redux-grid/blob/master/docs/USING_CUSTOM_EDITORS.md). I had to pass rowId to `Actions.EditorActions.updateCellValue` to update the cell value in the grid. I checked the source and it seems it expects the rowId as well. 

Just wanted to point out if the example in document needs to be updated to pass rowId?

I can submit the PR if required.

**Comment by bencripps** [comment]
Good catch! I've updated the docs accoridingly.

I think in the future we will pass an `onChange` method, similar to how we pass `onBlur` to abstract some of this work away. It doesn't make sense to force you to call `store.dispatch`, all you would need to provide is the updated value.

Thanks!
