### ISSUE TITLE
provide data for tree view does not work

### ISSUE THREAD

**Issue by raven001** [bencripps/react-redux-grid#118]
Type Error: this.props.data.map is not a function

**Comment by bencripps** [comment]
Thanks for posting the issue. This is a duplicate issue of #109 which has been resolved. Will be released as a patch version today.

**Comment by raven001** [comment]
Hi, still encountering the same issue

**Comment by raven001** [comment]
render() {
    const stateKey = 'tree';
    const treeConfig = {
    stateKey: 'tree-grid-1',
    gridType: 'tree', // either `tree` or `grid`,
    showTreeRootNode: false, // dont display root node of tree
    plugins,
    columns: [
        {
            dataIndex: 'category',
            name: 'Category',
            expandable: true // this will be the column that shows the nested hierarchy
        },
        {
            dataIndex: 'categoryCode',
            name: 'Category Code',
            expandable: true // can be set on multiple columns
        },
        {
            dataIndex: 'editable',
            name: 'Editable',
            expandable: false // will be displayed as flat data
        }
    ],
    data: {
        	"data" : {
        		"root" : {
        			"id" : -1,
        			"Name" : "Root",
        			"children" : [{
        					"id" : 1,
        					"parentId" : -1,
        					"Name" : "Category 1",
        					"GUID" : "8f7152dc-fed7-4a65-afcf-527fceb99865",
        					"Email" : "hgardnero6@ed.gov",
        					"Gender" : "Male",
        					"Address" : "605 Manley Park",
        					"Phone Number" : "31-(678)495-4134",
        					"children" : [{
        							"id" : 11,
        							"parentId" : 1,
        							"Name" : "Category 11",
        							"GUID" : "8f7152dc-fed7-4a65-afcf-527fceb991865",
        							"Email" : "hgardneross6@ed.gov",
        							"Gender" : "Male",
        							"Address" : "12 Manley Park",
        							"Phone Number" : "31-(678)495-4134"
        						}, {
        							"id" : 12,
        							"parentId" : 1,
        							"Name" : "Category 12",
        							"GUID" : "8f7152dc-fed7-4acf-527fceb991865",
        							"Email" : "hgardneross6@ed.gov",
        							"Gender" : "Male",
        							"Address" : "12 Manley Park",
        							"Phone Number" : "31-(678)495-4134",
        							"children" : [{
        									"id" : 121,
        									"parentId" : 12,
        									"Name" : "Category 121",
        									"GUID" : "8f7q2dc-fedsss7-4acf-527fceb991865",
        									"Email" : "hgoss6@eds.gov",
        									"Gender" : "Male",
        									"Address" : "21 fake Park",
        									"Phone Number" : "31-(678)495-4134"
        								}, {
        									"id" : 122,
        									"parentId" : 12,
        									"Name" : "Category 122",
        									"GUID" : "8f7q2dc-fed7-4acf-527fceb991865",
        									"Email" : "hgoss6@ed.gov",
        									"Gender" : "Male",
        									"Address" : "21 fake Park",
        									"Phone Number" : "31-(678)495-4134",
        									"children" : [{
        											"id" : 1221,
        											"parentId" : 122,
        											"Name" : "Category 1211",
        											"GUID" : "8f7q2dc-facf-527fceb991865",
        											"Email" : "hgossjdjdjdj6@ed.gov",
        											"Gender" : "Male",
        											"Address" : "21 fdjdjake Park",
        											"Phone Number" : "31-(678)495-4134"
        										}
        									]
        								}
        							]
        						}
        					]
        				}, {
        					"id" : 2,
        					"parentId" : -1,
        					"Name" : "Category 2",
        					"GUID" : "8f7q2dc-facf-527fcebdk=-jdjd991865",
        					"Email" : "hehehe@ed.gov",
        					"Gender" : "Male",
        					"Address" : "212 Park",
        					"Phone Number" : "31-(678)495-4134",
        					"children" : [{
        							"id" : 21,
        							"parentId" : 2,
        							"Name" : "Category 21",
        							"GUID" : "8f7q2dc-facf-527fcsw-jdjd991865",
        							"Email" : "hehehe@ed.gov",
        							"Gender" : "Male",
        							"Address" : "21112 Park",
        							"Phone Number" : "31-(678)495-4134",
        							"leaf" : false
        						}
        					]
        				}
        			]
        		}
        	}
        },
        stateKey
  };

**Comment by raven001** [comment]
using this sample
