### ISSUE TITLE
v5.1.9 requires redux-logger but only in dev-dependencies

### ISSUE THREAD

**Issue by Nihaux** [bencripps/react-redux-grid#119]
https://github.com/bencripps/react-redux-grid/blob/5.1.9/src/store/configureStore.js#L4

but

https://github.com/bencripps/react-redux-grid/blob/5.1.9/package.json#L103

**Comment by bencripps** [comment]
This issue has been resolved by #102 

Will be released this morning. Thanks for posting the issue!

**Comment by bencripps** [comment]
5.1.10 has been published. I'll update the changelogs and the release as soon as I can.

**Comment by Nihaux** [comment]
Thx :)
