### ISSUE TITLE
pager plugin does not update table when fetching new data

### ISSUE THREAD

**Issue by mickey159** [bencripps/react-redux-grid#121]
when i use my own pager, or the custom pager from the example in my project,
**the table does not render the new info**, even though i could see in the logs that the fetch did indeed happen (SET_DATA and SET_LOADING_STATE actions were called).
i'm using a remote data source, with my own function. (the default pager works fine).

**Comment by bencripps** [comment]
Take a look at how the custom pager works in the demo app:

https://github.com/bencripps/react-redux-grid-demo/tree/master/src/components/examples/custom-pager

Let me know if this helps clear up your issue.

**Comment by mickey159** [comment]
i tried using the custom pager again, however it still does not update the table, only the pager re-render itself.

**Comment by mickey159** [comment]
i found the problom.
thanks
