### ISSUE TITLE
Type Error: this.props.data.map is not a function still exist

### ISSUE THREAD

**Issue by raven001** [bencripps/react-redux-grid#122]
still encountering this issue when providing data to tree view

and this sample returns an error "invalid prop `data` of type `object` supplied to `Grid`, expected an array. Check the render method of `Connect(Grid)`."

render() {
    const stateKey = 'tree';
    const treeConfig = {
    stateKey: 'tree-grid-1',
    gridType: 'tree', // either `tree` or `grid`,
    showTreeRootNode: false, // dont display root node of tree
    plugins,
    columns: [
        {
            dataIndex: 'category',
            name: 'Category',
            expandable: true // this will be the column that shows the nested hierarchy
        },
        {
            dataIndex: 'categoryCode',
            name: 'Category Code',
            expandable: true // can be set on multiple columns
        },
        {
            dataIndex: 'editable',
            name: 'Editable',
            expandable: false // will be displayed as flat data
        }
    ],
    data:
    {
    		"root" : {
    			"id" : -1,
    			"Name" : "Root",
  			"children" : [{
  					"id" : 1,
  					"parentId" : -1,
  					"Name" : "Category 1",
  					"GUID" : "8f7152dc-fed7-4a65-afcf-527fceb99865",
  					"Email" : "hgardnero6@ed.gov",
  					"Gender" : "Male",
  					"Address" : "605 Manley Park",
  					"Phone Number" : "31-(678)495-4134",
            "leaf" : "false",
          },
        ]},
    },

     stateKey,
  };

**Comment by raven001** [comment]
stack = data.get(childIdentifier).map(toItem((0, _immutable.List)([-1]),

**Comment by bencripps** [comment]
Would you mind formatting this data; it's pretty hard to see what you're doing here. I've verified the bug has been fixed, and the tests are passing.

Would you mind running `npm cache clean && npm i`

If it's still happening, can you please provide more details, and format the code accordingly?

**Comment by raven001** [comment]
import React from 'react'
import { Grid } from 'react-redux-grid'
import { Map } from 'immutable';

export const plugins = {
    GRID_ACTIONS: {
        iconCls: 'action-icon',
        onMenuShow: ({ columns, rowData }) => {

            console.log('This event fires before menushow');

            if (rowData.isDisabled) {
                return ['menu-item-key'] // this field will now be disabled
            }

        },
        menu: [
            {
                text: 'Menu Item',
                key: 'menu-item-key',
                EVENT_HANDLER: () => {
                    alert('Im a menu Item Action');
                }
            }
        ]
    }
};

class Test2 extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    const treeConfig = {
    stateKey: 'tree-grid-1',
    gridType: 'tree', // either `tree` or `grid`,
    showTreeRootNode: false, // dont display root node of tree
    plugins,
    columns: [
        {
            dataIndex: 'category',
            name: 'Category',
            expandable: true // this will be the column that shows the nested hierarchy
        },
        {
            dataIndex: 'categoryCode',
            name: 'Category Code',
            expandable: true // can be set on multiple columns
        },
        {
            dataIndex: 'name',
            name: 'name',
            expandable: false // will be displayed as flat data
        }
    ],

     data:{
        "root":{
           "id":-1,
           "Name":"Root",
           "children":[
              {
                 "id":1,
                 "parentId":-1,
                 "Name":"Category 1",
                 "GUID":"8f7152dc-fed7-4a65-afcf-527fceb99865",
                 "Email":"hgardnero6@ed.gov",
                 "Gender":"Male",
                 "Address":"605 Manley Park",
                 "Phone Number":"31-(678)495-4134",
                 "children":[
                    {
                       "id":11,
                       "parentId":1,
                       "Name":"Category 11",
                       "GUID":"8f7152dc-fed7-4a65-afcf-527fceb991865",
                       "Email":"hgardneross6@ed.gov",
                       "Gender":"Male",
                       "Address":"12 Manley Park",
                       "Phone Number":"31-(678)495-4134"
                    },
                    {
                       "id":12,
                       "parentId":1,
                       "Name":"Category 12",
                       "GUID":"8f7152dc-fed7-4acf-527fceb991865",
                       "Email":"hgardneross6@ed.gov",
                       "Gender":"Male",
                       "Address":"12 Manley Park",
                       "Phone Number":"31-(678)495-4134",
                       "children":[
                          {
                             "id":121,
                             "parentId":12,
                             "Name":"Category 121",
                             "GUID":"8f7q2dc-fedsss7-4acf-527fceb991865",
                             "Email":"hgoss6@eds.gov",
                             "Gender":"Male",
                             "Address":"21 fake Park",
                             "Phone Number":"31-(678)495-4134"
                          },
                          {
                             "id":122,
                             "parentId":12,
                             "Name":"Category 122",
                             "GUID":"8f7q2dc-fed7-4acf-527fceb991865",
                             "Email":"hgoss6@ed.gov",
                             "Gender":"Male",
                             "Address":"21 fake Park",
                             "Phone Number":"31-(678)495-4134",
                             "children":[
                                {
                                   "id":1221,
                                   "parentId":122,
                                   "Name":"Category 1211",
                                   "GUID":"8f7q2dc-facf-527fceb991865",
                                   "Email":"hgossjdjdjdj6@ed.gov",
                                   "Gender":"Male",
                                   "Address":"21 fdjdjake Park",
                                   "Phone Number":"31-(678)495-4134"
                                }
                             ]
                          }
                       ]
                    }
                 ]
              },
              {
                 "id":2,
                 "parentId":-1,
                 "Name":"Category 2",
                 "GUID":"8f7q2dc-facf-527fcebdk=-jdjd991865",
                 "Email":"hehehe@ed.gov",
                 "Gender":"Male",
                 "Address":"212 Park",
                 "Phone Number":"31-(678)495-4134",
                 "children":[
                    {
                       "id":21,
                       "parentId":2,
                       "Name":"Category 21",
                       "GUID":"8f7q2dc-facf-527fcsw-jdjd991865",
                       "Email":"hehehe@ed.gov",
                       "Gender":"Male",
                       "Address":"21112 Park",
                       "Phone Number":"31-(678)495-4134",
                       "leaf":false
                    }
                 ]
              }
           ]
        }
     },
  };

    return (<Grid { ...treeConfig  } />)
  }
}

export default Test2

**Comment by raven001** [comment]
was basically trying to run the examples given, but  constantly having this error
"Warning: Failed propType: Invalid prop `data` of type `object` supplied to `Grid`, expected an array. Check the render method of `Connect(Grid)`." and this message on the grid 'No Data Available'.

**Comment by bencripps** [comment]
If you modify the `provider.jsx` in the `/demo` folder to the following, there are no errors. This is a tree grid using a local data source, and drag and drop is enabled. Closing this issue since this bug has been fixed and it seems like an error in your configuration. Let me know if you have any other issues.

```js
import React from 'react';
import Perf from 'react-addons-perf';
import { Provider } from 'react-redux';
import { Grid, Store, applyGridConfig } from '../src';

window.perf = Perf;
window.perf.start();

import {
    columns,
    data,
    pageSize,
    plugins,
    events,
    dataSource,
    treeDataSource,
    stateful,
    height,
    stateKey,
    treeData,
    examplePromiseDataSource
} from '../demo/demoData';

const config = {
    columns,
    // data,
    data: treeData,
    // dataSource: treeDataSource,
    // infinite: true,
    stateful: false,
    // dataSource: examplePromiseDataSource,
    dragAndDrop: true,
    gridType: 'tree',
    pageSize,
    plugins,
    events,
    stateKey
};

export default (
    <Provider store={ Store }>
        <Grid { ...config } />
    </Provider>
);
```
