### ISSUE TITLE
btoa call fails with UTF-8 encoded chracter in keyFromObject function

### ISSUE THREAD

**Issue by underwater222** [bencripps/react-redux-grid#125]
I am using UTF-8 for the column label and it create exception in chrome. It happens in the keyFromObject(...) function at keyGenerator.js.  I have changed the function as below and it works. btoa(unescape(encodeURIComponent(...))) is already implemented in the keyGenerator() function. Please change it so that it doesn't crash in Chrome.
Thanks.

function keyFromObject(obj, additionalStrings) {

    if (additionalStrings && Array.isArray(additionalStrings)) {
==>        return btoa(unescape(encodeURIComponent(additionalStrings.join('') + Object.keys(obj).map(function (k) {
            return obj[k];
        }).join(''))));
    }

==>    return btoa(unescape(encodeURIComponent(Object.keys(obj).map(function (k) {
        return obj[k];
    }).join(''))));
}
;

**Comment by bencripps** [comment]
Thanks for posting this issue! The utilities have been updated, and tests have been added around this use case. This will be published as part of this week's release 😃
