### ISSUE TITLE
addNewRow() : Insertion after a particular row.

### ISSUE THREAD

**Issue by underwater222** [bencripps/react-redux-grid#126]
When I use the grid for data entry, I would really like to insert a row after any arbitrary position, and also wants to rearrange rows by moving up and down. In order to test this, I have implemented a grid column's menu item 'Insert After' like this in my code;
```
GRID_ACTIONS: {
    menu: [{
            text: 'Insert After',
            EVENT_HANDLER: ({ metaData }) => {
                const rowIndex = metaData.rowIndex;
                store.dispatch(
                    Actions.EditorActions.addNewRow({ rowIndex, ...
```

However, In the function **addNewRow(_ref10)** of EditorAction.js(135), the rowIndex is always 0 after `var rowIndex = 0;` statement  and never gets chance to be changed until it is finally used in;
```
var addNewRow = exports.addNewRow = function addNewRow(_ref10) {
    var columns = _ref10.columns,
        data = _ref10.data,
        stateKey = _ref10.stateKey,
        _ref10$editMode = _ref10.editMode,
        editMode = _ref10$editMode === undefined ? 'inline' : _ref10$editMode,
++        _ref10$rowIndex = _ref10.rowIndex,
++        targetIndex = _ref10$editMode === undefined ? 0 : _ref10$rowIndex;

    return function (dispatch) {
        var rowId = (0, _keyGenerator.keyGenerator)('row', (0, _getNewRowId.getNewRowId)());
        var top = 43;
        var rowData = data || {};
--        var rowIndex = 0;
++        var rowIndex =targetIndex;
        var isCreate = true;

        dispatch({ type: _ActionTypes.ADD_NEW_ROW, stateKey: stateKey, rowId: rowId });

        dispatch(editRow({
            rowId: rowId,
            top: top,
            rowData: rowData,
            rowIndex: rowIndex,
            columns: columns,
            isCreate: isCreate,
            stateKey: stateKey,
            editMode: editMode
        }));
    };
};
```
Because of this, addNewRow() is always inserting a new row at the top.  Is it possible to create an empty row after a particular rowIndex which is passed as a parameter to addNewRow like above?

Also any suggestion in moving a row down or up from custom column menu?

Thanks.

**Comment by bencripps** [comment]
It would be really helpful if you could format these issues.

**Comment by underwater222** [comment]
I have updated this issue. Sorry for the ugly code format.

**Comment by bencripps** [comment]
Thank you! Agreed, this action should take a dynamic rowIndex, where it defaults to 0. 

Once this is implemented you can call this via a row-action -- since index is an argument to row actions, you can simply do => rowAction ++, or rowAction -- for above and below, respectively.

**Comment by bencripps** [comment]
Fix has been implemented -- will be published in next release.

**Comment by underwater222** [comment]
Hi Benjamin,

I have downloaded git and tested out your change, and it didn't work. To make it work I had to modify two files. Can you test out and include these changes in the next release. It will be greatly appreciated if I can see the change in the next release.

Thanks.

John.

src/editor/EditorActions.js
```
export const addNewRow = ({
    columns,
    data,
    stateKey,
    editMode = 'inline',
    rowIndex = 0,
    isCreate = true
}) => (dispatch) => {
    const rowId = keyGenerator('row', getNewRowId());
    const top = 43;
    const rowData = data || {};

--    dispatch({ type: ADD_NEW_ROW, stateKey, rowId});
++    dispatch({ type: ADD_NEW_ROW, stateKey, rowId, rowIndex });

    dispatch(
        editRow({
            rowId,
            top,
            rowData,
            rowIndex,
            columns,
            isCreate,
            stateKey,
            editMode
        })
    );
};
```

src/reducers/actionHelpers/plugins/datasource.js
```

export const addNewRow = (state, { rowId, stateKey, rowIndex }) => {
    const existingState = state.get(stateKey);
    const isEditing = existingState && existingState.get('isEditing');
    let data = existingState && existingState.get('data');

    if (existingState && isEditing) {
        return state;
    }

    let newRow = data
        && data.size > 0
        && data.get(0)
        ? data.get(0).map((k, v) => v = '')
        : fromJS({});

    newRow = newRow.set('_key', rowId);

    if (!data) {
        data = new List();
    }

 --   const newData = data.unshift(newRow);

 ++   rowIndex = rowIndex===undefined?0:rowIndex;
 ++   const newData = data.insert(rowIndex, newRow); // rather than adding at the head use insert at specific location
    
    const updated = existingState.merge({
        data: newData,
        proxy: data,
        isEditing: true,
        lastUpdate: generateLastUpdate(),
        total: newData.size
    });

    return state.setIn([stateKey], updated);
};
```

**Comment by bencripps** [comment]
Why not submit a PR with these changes?

**Comment by underwater222** [comment]
OK, I did 'npm t' on my changes and I got testing errors. I have changed the test I have added rowIndex parameter for ADD_NEW_ROW actions in the datasource.test.js, and added rowIndex to EditorAction.test.js like this;
```
        const action = {
            rowId: 'row-id',
            stateKey: 'test-grid',
            rowIndex: 0,
            type: ADD_NEW_ROW
        };
```
```
       expect(result)
            .toEqual([
                {
                    rowId: 'cm93LTE=',
                    stateKey: 'test-grid',
                    rowIndex: 0,
                    type: ADD_NEW_ROW
                },
```
Do you have any idea what I may be missing? The first error looks like this;


``
  The grid addNewRow Action
    ×Should set validation state
        Error: Expected [ { rowId: 'cm93LTE=', rowIndex: 0, stateKey: 'test-grid', type: '@@react-redux-grid/ADD_NEW_ROW' }, { columns: [ { dataIndex: 'col1', name: 'Col1' }, { dataIndex: 'col2', name: 'Col2' } ], editMode: 'inline', isCreate: true, rowId: 'cm93LTE=', rowIndex: 0, stateKey: 'test-grid', top: 43, type: '@@react-redux-grid/EDIT_ROW', values: {} } ] to equal [ { rowId: 'cm93LTE=', stateKey: 'test-grid', type: '@@react-redux-grid/ADD_NEW_ROW' }, { columns: [ { dataIndex: 'col1', name: 'Col1' }, { dataIndex: 'col2', name: 'Col2' } ], editMode: 'inline', isCreate: true, rowId: 'cm93LTE=', rowIndex: 0, stateKey: 'test-grid', top: 43, type: '@@react-redux-grid/EDIT_ROW', values: {} } ]
            at assert (D:/test2/react-redux-grid/webpack/webpack.test.js:21923:9)
            at Expectation.toEqual (D:/test2/react-redux-grid/webpack/webpack.test.js:33131:30)
            at Context.<anonymous> (D:/test2/react-redux-grid/webpack/webpack.test.js:42538:39)
``

**Comment by bencripps** [comment]
That test is fickle. Go ahead and submit the PR and I'll take a look.
