### ISSUE TITLE
What is the best way to destroy the grid? unmounted component warnings

### ISSUE THREAD

**Issue by headwinds** [bencripps/react-redux-grid#130]
Upon paging the grid or refreshing the search, we sometimes notice this "warning" in console... I think the React team used console.error because they appear in red which makes them look like breaking bugs, but I don't think they actually break anything... 

Do you think these warning would result from attempting to setState on the <Grid /> from a parent component's update if that grid no longer exists? I'm looking for the best way to remove it completely... or provide some logic to check if it's mounted or not to make these warnings go away

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the PagerToolbar component.
printWarning @ bundle.js:1681
bundle.js:1681 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the FixedHeader component.
printWarning @ bundle.js:1681
bundle.js:1681 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the PagerToolbar component.
```

**Comment by headwinds** [comment]
@bencripps 

I've got a fix for this... 

Since calling forceUpate will cause a component to re-render it effectively blows the grid away and I'm no longer seeing those warnings.

```
addDocumentWindowListeners(){
   const handleResize = (event) => {
      event.preventDefault(); 
      this.forceUpdate();        
    }

   if (window.addEventListener) {
        window.addEventListener('resize', handleResize, false);
    }
}
```

I call ```this.addDocumentWindowListeners()``` from the constructor of the main component.

**Comment by sorioinc** [comment]
Hi @headwinds did you fix the issue you reported or add the USING_RESIZE in the documentation? I stumbled upon a similar issue: 
```
invariant.js:42 Uncaught Error: Unable to find node on an unmounted component.
    at invariant (invariant.js:42)
    at assertIsMounted (react-dom.development.js:3770)
    at findCurrentFiberUsingSlowPath (react-dom.development.js:3805)
    at findCurrentHostFiber (react-dom.development.js:3886)
    at findHostInstance (react-dom.development.js:16824)
    at Object.findDOMNode (react-dom.development.js:17310)
    at FixedHeader.getScrollWidth (FixedHeader.js:352)
    at later (throttle.js:73)
```

I'm using react and react-dom 16.4.1.

@bencripps 

In this [line](https://github.com/bencripps/react-redux-grid/blob/master/src/components/layout/FixedHeader.jsx#L186) I see that the call to `getScrollWidth` is being debounced, so I think the `componentWillUnmount` is being hit, and the `getScrollWidth` can (and gets) called after that, hence the warning.

Am I correct? Do you think it's a bug?

**Comment by headwinds** [comment]
@sorioinc uggg sorry I checked - it looks like I never committed and have since lost the work - but it sounds like you have a good handle on the problem and potential fix
