### ISSUE TITLE
Error with webpack

### ISSUE THREAD

**Issue by partizanos** [bencripps/react-redux-grid#131]
I receive the following issue:

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! react-redux-grid@5.1.11 build: `webpack --pretty --config webpack/webpack.config.dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-grid@5.1.11 build script 'webpack --pretty --config webpack/webpack.config.dev.js'.
npm ERR! This is most likely a problem with the react-redux-grid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --pretty --config webpack/webpack.config.dev.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-grid
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls react-redux-grid
npm ERR! There is likely additional logging output above.

Steps until there after cloning the project and using npm install successfully.
I also tried to run:
`webpack --pretty --config webpack/webpack.config.dev.js`

and pretty argument is nor recognized:
`
Unknown argument: pretty
`

When trying to run:
` webpack --config webpack/webpack.config.dev.js`

I receive the following error:
`
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'eslint'.    object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.resolve.extensions[0] should not be empty.
`

**Comment by bencripps** [comment]
Hey, thanks for posting this issue! The upgrade to webpack2 is super recent, so these two tasks/configs are relics of the previous version. I've been thinking about it, and I don't think they really serve a purpose to the component -- there's really only two tasks grid needs:

1. `npm run dist` which creates the deployable assets
2. `npm start` (which relies on `npm run hot`) and creates a hot-reloadable version of the demo.

I think in response to this issue, I am simply going to delete the other two configs and their associated npm scripts. It's important to note, however, that even with this issue, grid is still fully functional.
