### ISSUE TITLE
How to update value of any specific cell in a row in react-redux-grid based on some custom action dispatched?

### ISSUE THREAD

**Issue by nirav-patel** [bencripps/react-redux-grid#134]
I\`m using editable react-redux-grid with some custom components.  Initially, I\`m fetching data from the Server using REST API and passing it into GRID. Let\`s assume table is having three columns (input field, status field & submit button). After each row, I have provided the column which contains one button (i.e., Submit) and when a user clicks on this button, I`m dispatching action to store the updated grid data on the server using REST API. Once the action gets completed, based on success or failure, FULFILLED or REJECTED action is being dispatched. I want to write a custom reducer to catch these actions and update specific cell value i.e. status = success or failed based on this result received from the server. 
As react-redux-grid manages the data in a state using its own reducers, I cannot directly update specific cell value in it using my custom action.
Is there any way I can achieve above requirement in react-redux-grid?

**Comment by bencripps** [comment]
You can update individual cell values by calling the internal grid action within your own custom action (not inside your own reducer, but on the return of your AJAX call:

```js
import { Actions } from 'react-redux-grid';

store.dispatch(
    Actions.EditorActions.updateCellValue({
        value: val, // the new value you want to update the cell with
        name: column.dataIndex, // the dataIndex for the column
        column, // the column being updated
        columns, // the array of all columns
        stateKey, // the stateKey for your grid
        rowId: row.key // and the rowId for the cell being updated
    })
);

**Comment by bencripps** [comment]
Closing this issue, let me know if you have more questions.
