### ISSUE TITLE
Question: How to easily get list of selected rows

### ISSUE THREAD

**Issue by axryp** [bencripps/react-redux-grid#135]
Sorry for perhaps asking the obvious, but what is the easiest way to get a list of currently selected rows in a multi-select scenario? A list of row indexes would be fine. 

I realize I can track selection myself using HANDLE_AFTER_SELECTION, but something easier would be awesome.

Thanks a lot

**Comment by bencripps** [comment]
This is not an obvious question! But this speaks to why having a `redux connected` component is useful -- rather than just a React component. 

```js
import { connect } from 'react-redux';
import { Grid } from 'react-redux-grid';

const MyGrid = props => {

    console.log(props.selectedRows);
    /* this will be an object containing the keyss of the selected rows, 
     * as well as an array of the indices of the selected rows
    **/

    return (
        <Grid 
	    stateKey="my-grid"
	    // ... rest of props
	/>
    );
};

export default connect((state, props) => ({
    selectedRows: state.selection.get('my-grid'),
}))(Pager);
```

**Comment by axryp** [comment]
Perfect! Thanks a lot.
