### ISSUE TITLE
loading spinner for grid

### ISSUE THREAD

**Issue by togonow** [bencripps/react-redux-grid#137]
i'm kind of new to react, wandering if the react grid has a loading spinner or i need to code that my self? i noticed two leads of (loading mask and loading-bar) but couldn't find an example on how to use them.

**Comment by bencripps** [comment]
By default the grid comes with a very simple loader plugin. It must be enabled for it to be visible:

```js
const plugins = {
    LOADER: {
        enabled: true
    }
}
```

Once you have it enabled, you can apply any custom CSS to change the look and feel. I've added an example on the demo site so you can get an idea.

http://react-redux-grid.herokuapp.com/CustomLoader

It's important to note that the component will handle when the loading mask should be visible/not visible. You can also set the loading state yourself by callling `Actions.LoaderActions.setLoadingState`.

**Comment by togonow** [comment]
thanks, will try that. Would appreciate if you update the react-redux-grid-demo repository

**Comment by bencripps** [comment]
Done.

**Comment by togonow** [comment]
awesome, thank you soo much
