### ISSUE TITLE
getting the new row order after a sort 

### ISSUE THREAD

**Issue by headwinds** [bencripps/react-redux-grid#141]
Where can I grab the current grid rows after sorting a column? I need to capture them in their new order. 

I can see 3 props on dataSource but they all seem to keep the original order not the new sorted order

```
const rows = this.props.dataSource.get('workbench').get('currentRecords').toJS();
const data = this.props.dataSource.get('workbench').get('data').toJS();
const proxy = this.props.dataSource.get('workbench').get('proxy').toJS();
```

Or is dataSource the wrong place to look? I thought currentRecords might have the new order but it doesn't change. 

dataSource is an ordered map - I'm guessing I don't want to use toJS() - but something else to return rows in their new order.

The grid reducer only has column header data right? But I feel it should also have current state of the grid including the current row order along with the column headers. 

Is there another reducer that would have this sorted state?

**Comment by headwinds** [comment]
@innopal I saw your were working with sort in the back issues - did you happen to run across where the sorted grid state is available in the store?

**Comment by bencripps** [comment]
@headwinds are we talking about local sort, where it's not retrieving the new order of the columns from an external resource (api)?

**Comment by headwinds** [comment]
@bencripps I'm not using the api - it's a local sort - I believe it's using the doLocalSort function.

Let's consider this [Sticky example](http://react-redux-grid.herokuapp.com/Sticky)

If I click on the address column, I can see all the rows change so that it's now sorted alphabetically by the address. 

Now if I try to get the rows in this new order...

```
const rows = this.props.dataSource.get('sticky').get('currentRecords').toJS();
```
In this case, rows has the original order not the new sorted order. But I want the sorted order which I hoped would be available in either grid or dataSource - obivously react-redux-grid is sorting the rows but is it storing that new sorted state somewhere?!

This is also providing me the opportunity to attempt to sort it myself and then save that state on my reducer since I know the key and the direction. Right now, I'm comparing an Immutablejs vs Rambajs sort which is interesting but not as powerful as if this library could take of that for me.

**Comment by headwinds** [comment]
@bencripps I went through datasource.test.js and I found you did provide a test for it - from this test, it seem "data" is what I want - this test proves it changes:

```
describe('The grid dataSource reducer sortData func', () => {
    beforeEach(() => resetLastUpdate());

    const inState = fromJS({
        'test-grid': {
            proxy: [
                { cell: 1 },
                { cell: 2 }
            ],
            data: [
                { cell: 1 },
                { cell: 2 }
            ],
            currentRecords: [
                { cell: 1 },
                { cell: 2 }
            ],
            total: 2,
            lastUpdate: 1
        }
    });

    it('Should update sort data', () => {

        const outState = fromJS({
            'test-grid': {
                proxy: [
                    { cell: 1 },
                    { cell: 2 }
                ],
                data: [
                    { cell: 2 },
                    { cell: 1 }
                ],
                currentRecords: [
                    { cell: 1 },
                    { cell: 2 }
                ],
                total: 2,
                lastUpdate: 1
            }
        });

        const action = {
            stateKey: 'test-grid',
            type: SORT_DATA,
            data: [
                { cell: 2 },
                { cell: 1 }
            ]
        };

        expect(
            dataSource(inState, action)
        ).toEqualImmutable(outState);

    });

});
```

Then I tried .toJSON() instead of .toJS() and now its providing the expected order - I guess they are different somehow?!

```
const sortedRows = this.props.dataSource.get('workbench').get('data').toJSON();
```

**Comment by headwinds** [comment]
Actually... I think this might be it

```
const sortedRows = this.props.dataSource.get('workbench').get('data');
const sortedRows = dataRecords.toArray().map(item => {
        return item.toJS()
      });
```

Then I know sortedRows is an array of objects in the new sorted order since map iterates in order - I hope

**Comment by headwinds** [comment]
I'll close this issue and then have you review an documentation update later
