### ISSUE TITLE
ReducerKeys as `string` in a Immutable Store not working

### ISSUE THREAD

**Issue by jca41** [bencripps/react-redux-grid#144]
In `stateGetter.js`:

`if (typeof props.reducerKeys === 'string') {
            return get(state[props.reducerKeys], key, entry);
   }`

Does not cover the scenario for an Immutable store.

Should be: 

`const isImmutable = typeof state.get === 'function';`
`if (typeof props.reducerKeys === 'string') {`
`const providedState = isImmutable ? state.get(props.reducerKeys):state[props.reducerKeys];`
           ` return get(providedState, key, entry);`
  ` }`

**Comment by bencripps** [comment]
Make the change and submit a pull request? :)

**Comment by jca41** [comment]
Sure, will do when i have the time :)

**Comment by bencripps** [comment]
This was fixed in #153
