### ISSUE TITLE
Is there a way to add custom component into the header element ?

### ISSUE THREAD

**Issue by jdakowicz** [bencripps/react-redux-grid#148]
I want to display something more than just a title on the header of the table. Is it possible to pass some custom component to the header?

**Comment by bencripps** [comment]
To replace the entire header, or to replace individual headers?

**Comment by jdakowicz** [comment]
To replace just one cell

**Comment by bencripps** [comment]
Each column definition can provide a `renderer` function where can return custom JSX.

**Comment by jdakowicz** [comment]
I am using the renderer for the regular cells. What I meant is the header cell which for now can display just the title. I want to add a custom dropdown there but don't really know is that possible and if yes how to do this.

**Comment by bencripps** [comment]
Right now there's not a way to do that :/

I will mark this issue as a feature request and hopefully get to this one soon, as it shouldn't be too involved.

**Comment by headwinds** [comment]
@jdakowicz In my project, I added my own custom header outside of the library and then hid the react-redux-grid header with an opacity of 0.

You could place a custom cell on top of the cell you wanted to replace making it appear like it belongs there. 
 

In my case, when you click the custom header, I've mapped the click events back to the hidden header.

```
handleColumnClick(event){
    event.preventDefault(); 
    const sortKey = event.target.dataset['sort'];

    this.state.columns[sortKey].selected = true; 

    // deselect the previously selected column
    const self = this;
    _.forIn(self.state.columns, function(value, key) {
       if (key !== sortKey) self.state.columns[key].selected = false;
    });
    
    let target = null; 
    switch(sortKey){
      case "column0" :
        target = document.getElementsByTagName("TH")[0]
        break;
      case "column1" :
        target = document.getElementsByTagName("TH")[1]
        break;
      case "column2" :
        target = document.getElementsByTagName("TH")[2]
        break;
    }

    setTimeout( ()=>{
      target.click();
    }, 200); 

  }
```

**Comment by jdakowicz** [comment]
Thank You @headwinds. I've made something similar to You.
