### ISSUE TITLE
Example for adding a row?

### ISSUE THREAD

**Issue by sclerck** [bencripps/react-redux-grid#149]
Hi Ben,
Great product! I'm trying to write a grid that updates based on live events. Is there a good example showing how to add a row? I've got this working by calling addNewRow followed by saveRow but I was wondering if there is something similar to updateRow? 

Thanks

**Comment by bencripps** [comment]
Right now, that's the only method of adding a row dynamically -- other than compiling the array of records yourself and calling `setData`. We could add a new action to bypass the requirement of saving the row before it becomes finalized. Let me know what you think, and we can mark this issue accordingly.

**Comment by sclerck** [comment]
Hi, thanks for the quick response. 

I think the ability to add a row that saves on completion would be great as this avoids having to make two requests - one to add the row, one to save it. 

Thanks

**Comment by bencripps** [comment]
Agreed, I've marked this as help-wanted but will add this feature as soon as I can.

**Comment by robskidmore** [comment]
I'm trying to do this myself at the moment @sclerck if you have an example of how you're tackling it currently I'd appreciate it.

**Comment by bencripps** [comment]
I don't think there's a work around except calling both actions sequentially right now. We will need to add a new action to grid, that simply does the insert into datasource.

**Comment by bencripps** [comment]
I've pushed a commit to master, you should be able to clone down and run the following action to insert a row.

```js
import { Actions } from 'react-redux-grid';

store.dispatch(
    Actions.GridActions.insertRow({
        stateKey: 'your-key',
        index: 1, // defaults to 0
        data: { someData: 1 }
    })
);
```

If this works for you, I will publish a new version.

**Comment by davorinrusevljan** [comment]
Is there a way to make some part of Redux store as datasource for the grid?

**Comment by bencripps** [comment]
No there's no way to do that.

**Comment by bencripps** [comment]
@sclerck have you had a chance to test if this works for you?

**Comment by sclerck** [comment]
Apologies for delay in getting back to you, i've been on vacation. 

I've tested this out and all works as expected. Thanks very much for the quick turnaround!
