### ISSUE TITLE
Partially editable grid

### ISSUE THREAD

**Issue by ksnyder** [bencripps/react-redux-grid#152]
I would like to have several columns that are not editable.  I tried setting `disabled: true` on the Name column for the Complex demo, but the field was still editable.  Am I understanding the meaning of this attribute correctly, or is there another way to accomplish the goal, such as a custom editor that just returns <span> instead of <input>?

**Comment by bencripps** [comment]
Sorry about the confusion, that prop should be `editable` and not `disabled`. This can either be a boolean or a function that returns true or false. I've updated the docs accordingly.
