### ISSUE TITLE
Tree data unclear

### ISSUE THREAD

**Issue by ksnyder** [bencripps/react-redux-grid#154]
I build the demo app, and in the Tree example added the plugin:

```javascript
EDITOR: {
                type: 'grid',
                enabled: true
            },
```
which worked fine. 

I copied the Tree column and data objects to my own app, which produced the warning:
```javascript
bundle.js:19060 Warning: Failed prop type: Invalid prop `data` of type `object` supplied to `Grid`, expected an array.
```

The grid still displayed data despite the warning, but when I added the EDITOR plugin to my app as I did to the demo, but it fails with this error:
```javascript
Uncaught TypeError: Cannot read property 'get' of null
```
from this line:
```javascript
var editorData = editorState.get(rowId) || new Map();
```

If I change the EDITOR type to 'inline', the 'get' error goes away and the data displays, but the lines are not editable (there is no icon to click on to put them in edit mode).

It's not clear to me why my app does not generate a rowId for the same data -- the only difference being mine is loading local data, instead of via dataSource.  I noticed the demo Tree loads both data (the same array used by other examples) as well as the nested object dataSource.

**Comment by bencripps** [comment]
This smells like a bug. I don't think anyone has used the tree with edit type `grid` yet -- and I don't have any tests around this. I will take a look and resolve.

**Comment by ksnyder** [comment]
Hi -- I was wondering if fixing this is on the roadmap.  We have to choose a tool soon for this, and other than this bug I like what I've seen in this library.

**Comment by bencripps** [comment]
Sorry for the delay on this! I've just pushed a fix for this one, and I'll cut a new release this evening.
