### ISSUE TITLE
How to remove grid with key 'a' ?

### ISSUE THREAD

**Issue by jdakowicz** [bencripps/react-redux-grid#155]
Is it possible to fully remove the grid with a specific stateKey from the store?

**Comment by bencripps** [comment]
Hmm, you mean not remove the component itself, but remove the parts of state in the store associated with the grid?e

**Comment by jdakowicz** [comment]
That's right.

**Comment by bencripps** [comment]
There's not currently a way to do that, but you could just remove the grid element from the DOM? Closing this issue as wont-fix, but if you find a way that works for you, please let me know.
