### ISSUE TITLE
Bulk deselection doesn't work

### ISSUE THREAD

**Issue by lkrnac** [bencripps/react-redux-grid#157]
First of all, thank you for this project, great work!

I tried this selection configuration:

                SELECTION_MODEL: {
                    mode: "checkbox-multi",
                    enabled: true,
                    allowDeselect: true,
                    activeCls: "active",
                    selectionEvent: "singleclick"
                },

Bulk select works (When I click on multi select checkbox, it selects all items), but this checkbox doesn't get selected. Further clicking on it doesn't deselect all items. I would expect behavior similar to this grid: https://paramquery.com/pro/demos/selection_checkbox

**Comment by bencripps** [comment]
Take a look at http://react-redux-grid.herokuapp.com/Complex, does this perform how you would expect it to?

Here is the code associated with this grid: https://github.com/bencripps/react-redux-grid-demo/blob/master/src/components/examples/complex/Complex.js

**Comment by bencripps** [comment]
Closing this issue for now, but let me know if you have any other issues.
