### ISSUE TITLE
custom sorting in remote

### ISSUE THREAD

**Issue by fearblackcat** [bencripps/react-redux-grid#158]
Hi, Ben
      Have it already be implemented for remote sorting?  I see this is a function in column array. But this function cannot get the grid component ? Is there any way to get the grid component in that function?
If it can be got, so I can implement by myself. Or maybe Ben you have more neat thought than mine.

Thanks!

**Comment by bencripps** [comment]
Not sure what you're asking, but I think you'd like a reference to the grid as part of the arguments to the sort function? If that's what you're asking, that kind of breaks the React pattern, since all updates to the component should be driven by state, and thus Redux actions.

What goal are you trying to accomplish, maybe I can find another way?

**Comment by fearblackcat** [comment]
Ben, thanks for answering my question. Since I read your documentation of Column Manager. I know you have already implemented remote sorting. But I need to add additional parameters for remote request. As the parameters also will be changed by react state.  I find a way to add custom parameters for remote sorting. I modified this file "react-redux-grid/dist/components/core/ColumnManager.js".
In doSort function:

            var propName = (0, _getData.nameFromDataIndex)(column);

            var sortParams = {
                sort: {
		    querytypes: this.config.getRequestParameters(),   // this is my new addition code
                    property: propName,
                    direction: direction
                }
            };


and  modified the COLUMN_MANAGER of plugins

               COLUMN_MANAGER: {
                    ......
                    getRequestParameters: ()=>{return this.props.stateparas;},   //this is my new addition code
                    sortable: {
                        enabled: true,
                        method: 'remote',
                        sortingSource: 'http://url/datasource'
                    }
                }


So this is my goal.  Do you have better ways that can overwrite the doSort function?  I think my way is not perfect cause I changed the source code.

**Comment by headwinds** [comment]
@fearblackcat @bencripps in our project, we accomplished remote sorting using the custom pager example which includes [this api](https://github.com/bencripps/react-redux-grid-demo/blob/master/src/components/examples/custom-pager/Api.js). We didn't need to touch column manager. 

Along with passing the index, we added the ability to pass the sort key and direction on the request.

**Comment by bencripps** [comment]
I think we can close this one due to the work accomplished by #162
