### ISSUE TITLE
Bulk deseletion doesn't work v2

### ISSUE THREAD

**Issue by lkrnac** [bencripps/react-redux-grid#160]
As #157 was closed, opening new issue. I created minimal reproducable example https://github.com/lkrnac/react-redux-grid-multiselect-issue. react-redux-grid code is in `TestGrid.js` file

Original report:
Bulk select works (When I click on multi select checkbox, it selects all items), but this checkbox doesn't get selected. Further clicking on it doesn't deselect all items. I would expect behavior similar to this grid: https://paramquery.com/pro/demos/selection_checkbox

**Comment by brandonflowers** [comment]
this is true and should be fixed but in the meantime, there is a bulk deselect type...

```'@@react-redux-grid/DESELECT_ALL'```

...that you can listen to in your reducer and then loop through the rows to manually deselect them all  - I bet you did this ;-D - I had to do this in my project.

It goes along with this other related [bug deselect issue](https://github.com/bencripps/react-redux-grid/issues/145)

**Comment by headwinds** [comment]
this is true and should be fixed but in the meantime, there is a bulk deselect type...

```
case "@@react-redux-grid/DESELECT_ALL":  
      return Object.assign({}, state, {
        allRowsDeselected: true,
      })         
```

...that you can listen to in your reducer and then loop through the rows to manually deselect them all  - I bet you did this ;-D - I had to do this in my project.

It goes along with this other related [bulk deselect issue](https://github.com/bencripps/react-redux-grid/issues/145)

**Comment by lkrnac** [comment]
@headwinds. Thanks for workaround!

**Comment by bencripps** [comment]
This has been resolved; it will shipped in the next release.
