### ISSUE TITLE
'No Data Available' shows when trying to setup 

### ISSUE THREAD

**Issue by MHultman** [bencripps/react-redux-grid#165]
I'm setting up a component for use in some other and trying to just make the first implementation to work but getting "No Data Available" as result in the grid.

I can't seem to find what i did wrong. 

    import` React from 'react';
    import { Grid } from 'react-redux-grid';
    import Store from '../../store';
    import {columns,data,pageSize,events} from './GridDemoData';

    class GridComponent extends React.Component {
      constructor(props, context) {
        super(props, context);
        this.state = {};
      }
      render(){

        const simpleData = {
          columns,
          data,
          pageSize,
          plugins: {},
          events,
          Store,
          stateKey: 'simple'
        };

        return (
          <div>
            <Grid
              {...simpleData}
            />
          </div>
        );
      }
    }

    export default (GridComponent);

I'm using the exact same demoData file as in the demos. 
No errors, no nothing.

Please help!

**Comment by bencripps** [comment]
Are you importing the grid reducers?
