### ISSUE TITLE
PropTypes (oneOfType) error when requiring Grid

### ISSUE THREAD

**Issue by russelldc** [bencripps/react-redux-grid#166]
`warning.js:36 Warning: Invalid argument supplid to oneOfType. Expected an array of check functions, but received string at index 0.`

The error points to [TreeArrow.js:136, found here](https://github.com/bencripps/react-redux-grid/blob/9e1b8f1a67ae3372e872ac6d07ca933614b4461f/src/components/layout/table-row/row/cell/TreeArrow.jsx#L123).

>  gridType: oneOfType([
        'grid', 'tree'
    ]),

It looks like this code should be using oneOf, rather than oneOfType, but I'm not too familiar with PropTypes.

**Comment by bencripps** [comment]
Thanks for posting the issue, this has been resolved!
