### ISSUE TITLE
Select cell event

### ISSUE THREAD

**Issue by kamou31** [bencripps/react-redux-grid#173]
Hello, 

I have a big issue and i'm not able to find in the documentation of to do this.
I need to have a click event on a particular cell for each row. But only on this cell.

I didn't find how to do this : 
HANDLE_CELL_CLICK event does not have the information of the cell clicked (only the whole row), and the HANDLE_CLICK event in the column definition is only triggered when i click on the column header.

I also tried to add a onClick event in the column rendering attribute but the event is triggered even if click on another cell...

Can you help me please?

Thank you

**Comment by bencripps** [comment]
I assume you found what you needed @kamou31 ?

**Comment by kamou31** [comment]
Hello.

 Yes and i felt stupid so i closed this issue.

Thank you for this great component !

Le 22 août 2017 00:53, Benjamin Cripps <notifications@github.com> a écrit :

I assume you found what you needed @kamou31<https://github.com/kamou31> ?

**Comment by pthieu** [comment]
@kamou31 can you explain what you found?
