### ISSUE TITLE
stateGetter failing on Non-Immutable store

### ISSUE THREAD

**Issue by bellmoose** [bencripps/react-redux-grid#177]
The get method in stateGetter is failing when using a non Immutable store:
`

export const get = (state, key, entry) => {

    if (!state) {
        return null;
    }

    const isImmutable = typeof state.get === 'function';
    const stateItem = isImmutable
        ? state.get(key)
        : state[key];

    if (!stateItem) {
        return null;
    }

    return stateItem.get(entry);
};

`

Last line should be
`
return isImmutable ? stateItem.get(entry) : stateItem[entry];
`

Trying to put together a Pull Request, but having some issues with the build for some reason.

Associated test in stateGetter.test.js
`

it('Should return state when its not stored using immutable', () => {
        const state = { data: { thing: [1] } };
        const props = {};

        expect(
            stateGetter(state, props, 'data', 'thing')
        ).toEqual(List([1]));
    });
});

`

**Comment by bencripps** [comment]
A pull request would be great, what build issues are you having?

**Comment by bellmoose** [comment]
Needed to upgrade node apparently.  Working on getting a PR working.

**Comment by bencripps** [comment]
This issue was resolved with #179 179
