### ISSUE TITLE
Question: How define column-cells alignment ?

### ISSUE THREAD

**Issue by pcclickbit** [bencripps/react-redux-grid#178]
Hi,

Im starting to use react-redux-grid.
The current report has dates and numeric values.
It would be desirable the columns with numeric data are aligned to the right
How can I define the column-cells  alignment?

![image](https://user-images.githubusercontent.com/11739293/30037602-c4aac77a-9179-11e7-893f-50ccf268727f.png)

thanks.

**Comment by bencripps** [comment]
I would use a custom renderer which would allow you to write some custom CSS for these columns; something like:

```js
const columns = [
    {
        name: 'Risk',
        dataIndex: 'risk',
        renderer: ({ column, value, row }) => {

            return (
                <span className="numeric-column">
                    {value}
                </span>
                );
        }
    }
];
```

And then simply add some CSS:

```css
.numeric-column {
    text-align: right;
}
```

For more information about renderers, you can check out these [docs](https://github.com/bencripps/react-redux-grid/blob/master/docs/USING_CUSTOM_RENDERERS.md).
