### ISSUE TITLE
Nested reducer documentation needs update

### ISSUE THREAD

**Issue by vg-stan** [bencripps/react-redux-grid#185]
Hi there, just testing out react-redux-grid and found that the documentation isn't quite right for using a nested reducer as the combined rootReducer isn't exported by the module currently.  

https://github.com/bencripps/react-redux-grid/blob/master/docs/USING_GRID_REDUCERS.md

```
import { Reducers as rootReducer } from 'react-redux-grid';
....
export const rootReducer = combineReducers({
    myAppReducer,
    myDataReducer,
    nested: rootReducer
});

```
should be:

```
import { Reducers as gridReducers } from 'react-redux-grid';
....
export const rootReducer = combineReducers({
    myAppReducer,
    myDataReducer,
    nested: combineReducers(gridReducers)
});

```
unless the intent is to expose the rootReducer exported from src/reducers/index.js.  Thanks!

**Comment by bencripps** [comment]
Thanks! If you have a min, you could submit a pull request, or I will get to it as soon as I can!
