### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by PMByrne** [bencripps/react-redux-grid#186]
Hi,

react-redux-grid is preventing me from updating to v16 because it has a hard dependency on react and react DOM.

Could new peer dependencies be created and the hard dependencies moved to devDependencies?

```javascript
"peerDependencies": {
    "font-awesome": "^4.0.0",
    "react": ">=15.0.0 <17.0.0",
    "react-dom": ">=15.0.0 <17.0.0"
}
```

I would probably consider making the redux dependencies peer dependencies as well.

I do realize this is day 0 and will try to get a pull request made if you can't get to this soon.

**Comment by bencripps** [comment]
This is a great point, and a pull request would be greatly appreciated!

**Comment by bencripps** [comment]
Thanks for creating this issue, this has been resolved -- a new publish is coming soon.
