### ISSUE TITLE
Instantiating Grid as Tree with example objects throws.

### ISSUE THREAD

**Issue by atanasbozhkov** [bencripps/react-redux-grid#187]
I'm trying to instantiate a Tree Grid as per the examples.
I'm using the test data structure obtained from the [FAQ here](https://github.com/bencripps/react-redux-grid/blob/master/docs/USING_TREE.md#more-information-about-tree)

However if I pass that object to the data prop on the tree config object - I get:

    Failed prop type: Invalid prop `data` of type `object` supplied to `Grid`, expected an array.

which I guess is fair enough since the data object is not an array. 

I also tried instantiating it with the testData object from the [example repo](https://github.com/bencripps/react-redux-grid-demo/blob/master/src/components/examples/data/demodata.js) - but it seems to fail on  `treeToFlatList node_modules/react-redux-grid/dist/util/treeToFlatList.js:32`

     stack = data.get(childIdentifier).map(toItem((0, _immutable.List)([-1]), (0, _immutable.List)([0]), childIdentifier));
     >TypeError: Cannot read property 'map' of undefined

which I'm guess means that it's expecting a diffrently shaped object?

If someone can shed some light on the issue I'd appreciate it greatly. 

Thanks,
Nasco

**Comment by bencripps** [comment]
Can you post the entire object you're passing to the Grid component? The data section can be shortened, but I'd just like to see the other props you're passing and a small sample of the data.

**Comment by atanasbozhkov** [comment]
I'm passing a slimmed-down version of the example's `complexData` objects.

It look like this currently:

     const complexData = {
        showTreeRootNode: false,
        gridType: 'tree',
        dragAndDrop: true,
        columns: [
            {
                name: 'Name',
                width: '30%',
                className: 'additional-class',
                dataIndex: 'Name',
                sortable: false,
                expandable: true
            },
            {
                name: 'Phone Number',
                dataIndex: 'Phone Number',
                sortable: false,
                className: 'additional-class'
            },
            {
                name: 'Email',
                dataIndex: 'Email',
                sortable: false,
                className: 'additional-class',
                defaultSortDirection: 'descend'
            },
            {
                name: 'Address',
                dataIndex: 'Address',
                sortable: false,
                className: 'additional-class'
            }
        ],
        data,
        plugins: {
            ...plugins,
            GRID_ACTIONS: null,
            SELECTION_MODEL: {
                mode: 'single'
            },
            PAGER: {
                enabled: false
            },
            BULK_ACTIONS: {
                enabled: false
            }
        },
        events,
        store,
        stateKey: 'tree'
    };

The column definitions are off for the data from the FAQ section - but they should work fine with the test data from the  example repo.

**Comment by bencripps** [comment]
If you are building a tree, you need to pass tree shaped data -- see this file

https://github.com/bencripps/react-redux-grid/blob/master/demo/data.js#L1004

**Comment by bencripps** [comment]
Let me know if that didn't resolve your issue -- closing this for now.
