### ISSUE TITLE
'state[operation] is not a function' on refresh

### ISSUE THREAD

**Issue by slax0rr** [bencripps/react-redux-grid#189]
Hello,

I am getting the following error when refreshing my application:
```
bundle.js:68834 Uncaught TypeError: state[operation] is not a function
    at getUpdatedDataRecord (bundle.js:68834)
    at setColumns (bundle.js:87977)
    at bundle.js:68256
    at combination (bundle.js:53685)
    at bundle.js:12525
    at computeNextEntry (<anonymous>:2:27469)
    at recomputeStates (<anonymous>:2:27769)
    at <anonymous>:2:31382
    at Object.dispatch (bundle.js:12141)
    at dispatch (<anonymous>:2:31875)
```

Here's my grid configuration:
```javascript
const plugins = {
  EDITOR: {
    type: 'inline',
    enabled: false,
    focusOnEdit: true
  },
  LOADER: {
    enabled: true
  }
};

const columns = [{
  name: 'Account',
  dataIndex: 'account',
  width: '70%',
  editable: false,
  className: 'account-col'
}, {
  name: 'Ballance',
  dataIndex: 'ballance',
  width: '30%',
  editabled: false,
  className: 'ballance-col'
}];

const data = [{
  account: 'Account 1',
  ballance: '900.00€'
}, {
  account: 'Account 2',
  ballance: '600.00€'
}];

export default {
  plugins,
  columns,
  data,
  height: 250,
  classNames: [
    'accounts',
    'financer'
  ],
  stateKey: 'accounts-grid'
};
```

And how I use it:
```javascript
// ...
import gridData from './data.js';
// ...
export class Accounts extends Component {
  render() {
    return (
        // ...
          <Grid {...gridData} />
        // ...
    )
  }
}
```

I am importing reducers as:
```javascript
// ...
import { Reducers as gridReducers } from 'react-redux-grid';
// ...

export default {
// ...
  ...gridReducers,
// ...
};
```

The above gets fed into combineReducers. I am also using the `redux-persist` component to persist my state and store across refreshes. I have tried debugging this to no avail. I have hit a dead end, and am reaching out to you for help with this issue.

**Comment by slax0rr** [comment]
I can confirm that this error does not happen when the `redux-persist` component is not in use.

**Comment by bencripps** [comment]
This sounds like a use-case I'd like to support. Do you have the code in a place I could clone, and run locally? It would help me figure out the core issue.

**Comment by slax0rr** [comment]
Unfortunatelly the project is not yet public, I will try to reproduce it in an empty project. Will get back to you ASAP.

**Comment by slax0rr** [comment]
Sorry for another double-post. Recreated and ready to be cloned here: https://github.com/slax0rr/react-redux-grid-persist

**Comment by bencripps** [comment]
After a little research it looks like redux-persist actually mutates the state atom from an immutable object to a plain JS object -- which breaks the Grid component, since the grid manages it's internal state via immutable objects.

To be honest, I don't think it's reasonable for Grid to expect the state atom to be mutated in this way, so I don't think we'll be updated the component to support this feature. Sorry about that!
