### ISSUE TITLE
Issue with Ie11

### ISSUE THREAD

**Issue by sudipta-trip** [bencripps/react-redux-grid#190]
I get the following error on IE 11.
 Unable to get property '__reactInternalInstance$yzdkl2pqwp9r' of undefined or null reference.
File: bundle.js, Line: 15685, Column: 4

**Comment by bencripps** [comment]
Hmm, that's not really enough information to help. Can you find out which line (from the non-minified code) is throwing? It also seems like this could have to do with your implementation?
