### ISSUE TITLE
Removing all visible columns throws errors

### ISSUE THREAD

**Issue by Vanderslice** [bencripps/react-redux-grid#192]
Just need to add a unique key to empty cells and update the way we're importing Cell in EmptyCell.jsx

**Repro Steps**: (Using the Demo Grid)
- Click the column headers' action button
- Uncheck all visible columns

**Expected Results**:
- All columns should be removed
- No errors

**Actual Results**:
- Throws the following errors
-- EmptyCell doesn't have a unique key
-- React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `EmptyCell`.

**Comment by bencripps** [comment]
Thanks for posting, and fixing this issue!
