### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by chenEdgar** [bencripps/react-redux-grid#194]
system: win10
browser: chrome version  62.0.3202.75
node: 8.1.2
npm: 5.0.3

I copyed the tree demo in my project, code followed:
![image](https://user-images.githubusercontent.com/12596622/34246763-e2b77150-e66a-11e7-9563-7df88ba2dc7d.png)

and then I suffered this bug as followed:
![image](https://user-images.githubusercontent.com/12596622/34246797-01a220c4-e66b-11e7-996c-dfcd94eaca08.png)

source code as followed:
![image](https://user-images.githubusercontent.com/12596622/34246851-4091779e-e66b-11e7-8157-465c79dfe684.png)

I don't know why I got the problem.

**Comment by bencripps** [comment]
It's odd you're seeing this, since `navigator` is a common global -- especially in that version of chrome -- however, we could probably fix this by prefixing the var with `window`.

Some thing like:
```js
window.navigator && test(window.navigator)
```

Pull requests welcome!

**Comment by chenEdgar** [comment]
I've tried this but failed again. window is not defined...

**Comment by bencripps** [comment]
I'm not sure how window could be undefined? https://developer.mozilla.org/en-US/docs/Web/API/Window
