### ISSUE TITLE
Error message documentation possibly out of date

### ISSUE THREAD

**Issue by tvand7093** [bencripps/react-redux-grid#195]
I have been trying to use the built in error message functionality, but it seems to never display. I am returning null from a data source function and based on the source code I would expect that to trigger the message. However, the reducer action is called, but no message is displayed.

It would be great if there was more documentation on how to use the error message functionality so that people do not need to dig into source code to figure that part out. Or perhaps an actual demo that intentionally triggers the message, since most demos setup the error handler, but never actually utilize it.

**Comment by bencripps** [comment]
Looks like there were a few issues with the ErrorHandler module. I've addressed those, as well as created an example for the demo site.

**Comment by bencripps** [comment]
Demo: http://react-redux-grid.herokuapp.com/ErrorMessage
Code: https://github.com/bencripps/react-redux-grid-demo/blob/master/src/components/examples/ErrorMessage.js
