### ISSUE TITLE
[Question] Can we do paging by scrolling?

### ISSUE THREAD

**Issue by cechzhou** [bencripps/react-redux-grid#197]
I want to get remote data by scrolling, like the infinite loading, but I don't know how to send request and set data, are there some properties?

**Comment by bencripps** [comment]
These closest thing we have currently to infinite scroll is the [stress](https://github.com/bencripps/react-redux-grid-demo/blob/master/src/components/examples/Stress.js) example -- it doesn't make requests as you scroll, but it enables you load the initial set of data, and then lazy-load the rest of the records.

It will appear as though the records will have been there the whole time, and the page wont slow down even if you have thousands of records.
