### ISSUE TITLE
Infinite Scroll: Enhancement

### ISSUE THREAD

**Issue by qosmy-michael** [bencripps/react-redux-grid#2]
Hi Ben,

I really like what you've done - very nice, one of the best UIs I've seen

This is an enhancement request for infinite scroll capability - makes the grid feel more fluid and helps brings the data to life.

Ideally for both horizontal and vertically so one can scroll through a large number of columns (perhaps with one fixed), and vertical with hidden background fetches for the next page of data.  A little momentum in the animation is fun too. :)

Thanks,

Michael

**Comment by bencripps** [comment]
Thanks @qosmy-michael, I think thats a great feature. Currently I'm working on getting all components fully tested -- once I've got that complete, `infinite scroll` is at the top of the list for new features.

**Comment by bencripps** [comment]
With the addition of `infinite` and the `sticky` I think this feature request can be closed.
