### ISSUE TITLE
working with a simple rest service

### ISSUE THREAD

**Issue by kkwak** [bencripps/react-redux-grid#21]
the demo is great - but I don't know if it actually does anything to the back end.

1. save after edit
2. delete
3. add rows

Not sure how I'd use the GRID_ACTIONS plugin to delete the row
  EVENT_HANDLER(data) { ... }
data.metaData seems to have the row in question - but what's the intended pattern to update the ui+server?

I figure..
1. have all the relevant fetch() with uris all in scope and get a promise
2. promise.then -> store.dispatch a new SET_DATA without the referenced row to update the ui
am I way off? (I'm new to everything so let me know if I speak nonsense.. :D)
if I'm on the right path - it'd be super helpful to pass the store when calling EVENT_HANDLER.

**Enhancement Request**
Ideally, I'd like to configure the dataSource function to actually not only load, but have other actions attached..  
dataSource {
  load() {}
  update(row) {}
  delete(row) {}
}
That way for (1) everything is already in scope -- anyway that'd be a major change.

**Comment by bencripps** [comment]
You are correct, the demo data doesn't have any `rest` functionality. I like your enhancement request, but this is a big change so ideally I'd like to think about it some before making these changes. 

The best pattern for this is: 

`constants.js`;

````js
export const API_READ = 'api/read/route';
export const API_UPDATE = 'api/update/route';
export const API_DELETE = 'api/delete/route'; 
````

`grid.js`

````js
import { apiDelete, apiRead } from './api';
import { GridActions } from 'react-redux-grid';

const config = {
    plugins: {
         GRID_ACTIONS: {
             menu: [
                {
                    text: 'delete',
                    EVENT_HANDLER: ({ store, metaData }) => {
                        apiDelete(metaData).then(() => {
                            store.dispatch(
                                GridActions.DataSource.getAsyncData({
                                    stateKey: 'my-grid',
                                    dataSource: apiRead
                                });
                            );
                        })
                    }
                }
             ]
         }
    }
};
````

I like the idea of making the `dataSource` an object with three keys, but it also seems a little more restrictive than the current design. Like I said, I'm going to think about it for a bit.

**Comment by kkwak** [comment]
minus a couple typos, that worked for me. 
`
import { Actions } from 'react-redux-grid'
Actions.GridActions.getAsyncData(...)
`
also "store" doesn't get passed in to the EVENT_HANDLER. I had to bring it in scope, which isn't a big deal.

I need a way to "ADD" to rows to the grid in edit mode - if you have ideas, let me know.. 

I'm going through the codebase, but it's quite large and I'm not a js dev.

**Comment by bencripps** [comment]
There is an `addRow` action exposed by the grid.

````js
export function addNewRow({ columns, data, stateKey }) {

    return (dispatch) => {
        const rowId = keyGenerator('row', 0);
        const top = 43;
        const rowData = data || {};
        const rowIndex = 0;
        const isCreate = true;

        dispatch({ type: ADD_NEW_ROW, stateKey });

        dispatch(
            editRow({
                rowId,
                top,
                rowData,
                rowIndex,
                columns,
                isCreate,
                stateKey
            })
        );
    };
}
````

You can pass rowData to it, so the new row will be populated with that data, otherwise it will be empty.

**Comment by kkwak** [comment]
works perfectly - I suppose these actions are meant to be the api of the grid.. thanks!
