### ISSUE TITLE
Nested object property as column value

### ISSUE THREAD

**Issue by mgscreativa** [bencripps/react-redux-grid#215]
Hi! sorry to bother. Do your component support displaying values of a nested object property?

I have this object 
```
const Act = 
{
    "_id" : "vdenftDD8gxn2ZgRe",
    "userId" : "AdebgC6dXLE4aqLGg",
    "routine" : {
        "_id" : "G9nw8Bo3hgQnnTyAp",
        "name" : "Routine Name",
    },
    "createdAt" : "2018-05-03T01:36:09.694Z"
}
```
And I need to have a column populated with **Act.routine.name**, is that possible?

Thanks!

**Comment by bencripps** [comment]
You should be able to acheive this by adding a `renderer` property to your column:

```
name: 'act',
renderer: ({ column, value, row }) => (
    <span> Name: { value.routine.name } </span>
)
```

**Comment by mgscreativa** [comment]
Cooool! thanks a lot!
