### ISSUE TITLE
not compatible with bootstrap css

### ISSUE THREAD

**Issue by kkwak** [bencripps/react-redux-grid#24]
There is an entry in bootstrap css:
```
button,input,optgroup,select,textarea{margin:0;font:inherit;color:inherit} 
```
Which for some reason makes the editor show in color:white, aka not visible.

This is due to the entry src/style/components/row.styl
```
         &.{editclass}
            color whitecolor       <--- this guy
             background-color editcolor
```
Not sure why it's white on grey, but this doesn't work with bootstrap - not sure if this is a problem for others, but I can't seem to manually override it (due to the way webpack is sourcing the css)
(Perhaps if I knew webpack better I could order it properly and load it.. :D)

thoughts? can we remove this line? as the 'user agent stylesheet' makes the input background to white..
or perhaps override the default input background to the editor color.. or at least to inherit..

**Comment by bencripps** [comment]
Why not simply use a more specific rule? Do you have a class on the container for the grid?

Let's say your container class was `my-class-name`.

To get the desired color, you could simply have a more specific class:

````css
.my-class-name .react-grid-row.react-grid-edit {
    color: inherit;
}
````

**Comment by kkwak** [comment]
didn't have time to try - but the whole *-edit is generated and the classname is specified there. So I'd have to resolve it at a closer place - and there is no place unless I override the editor.

I'll try to make time to look over it (I've overwritten the bootstrap css as we're not using a cdn, as a workaround)

**Comment by bencripps** [comment]
Did you get a chance to check on this one, @kkwak?

**Comment by kkwak** [comment]
just now. everything is generated and can't override the css - especially as it specifies the color/background-color..

the column def allows for a css class but that only affects the header table and not the rows. Even if, the css is for the EDIT classname, so it wouldn't work anyway.

Options would be:
1. don't set the color/background-color (I like this)
2. allow the column className to affect each row too (and in edit mode)
  (in fact it should do this anyway I'd think.. because I don't know what use case would want to specify the className for the column header only..)

Cheers.

**Comment by bencripps** [comment]
Why are you doing this with JavaScript -- can't you simply specify a more specific css class to override the default grid css? The grid css is simple, and meant to be overridden with a more specific rule set?

**Comment by bencripps** [comment]
@kkwak checking in, but if there's no issue, I'd like to get this one closed.

**Comment by kkwak** [comment]
ahh totally dropped the ball - got pushed off on to another project. Please close - I'll work around this.
