### ISSUE TITLE
unable to save when multiple grids are available

### ISSUE THREAD

**Issue by kkwak** [bencripps/react-redux-grid#25]
I've got a tablist with each tab managing a grid.
one tab with one grid works without any problems. 
When I add another grid (with a different statekey) it breaks.

This error: 
```
// Uncaught TypeError: Cannot read property 'values' of undefined
// Button.jsx
export const onButtonClick 
```

I also get this error: 
```
// Uncaught TypeError: Cannot read property 'top' of undefined
// Inline.jsx
export const resetEditorPosition
```

I'll try to debug more later on, but I don't think this is anything I'm doing wrong on my side.
The FIRST tab always works. It's the subsequent tab that doesn't - so if I switch it around, it still fails for the second tab.. 

Let me know if this is a valid bug.

**Comment by bencripps** [comment]
This definitely sounds like a bug -- I will investigate and commit the fix tomorrow morning. Good catch!

**Comment by bencripps** [comment]
Ok, this issue has been fixed; the way I was selecting the editor (on edit actions, like `resetEditorPosition`) needed to be scoped to the actionable grid. 

No changes should be necessary from your end, simply reinstall grid from master.

Thanks for posting this issue -- this was an awesome catch!

**Comment by kkwak** [comment]
Great! I'll try this out tomorrow and get back to you.
