### ISSUE TITLE
Sortable is not working!

### ISSUE THREAD

**Issue by innopal** [bencripps/react-redux-grid#29]
Hi Ben,

Great component! Well done. 
I can't seem to be able to get the sort icons show on column headers.
Even in your demo page (http://react-redux-grid.herokuapp.com/) it seems like they are hidden despite the fact that you have them enabled for 3 columns.

It seems like they are hidden for some reason:
.react-grid-header th .react-grid-sort-handle {
    float: left;
    transition-duration: 150ms;
    transition-property: opacity;
    transition-timing-function: cubic-bezier(0.17, 0.67, 0.83, 0.67);
    **visibility: hidden;**
}

Is there anything else needs to be set other than simply setting sortable: true in column definition?

Cheers

**Comment by bencripps** [comment]
Hmm, they are hidden until you click them. Once clicked, they become visible. If you click another sortable column, that column arrow then shows, and the previous column header is then invisible.

Let me know if this isn't working as designed.

If you'd like, you can simply create a more specific class to make these arrows always visible, but since sorting can only work on one column at a time, that could be problematic.

Thanks!

**Comment by innopal** [comment]
What you explained makes sense, except that there is nothing to click.
I am testing on chrome and I am wondering what browser are you testing on.
There are some noticeable differences between Chrome and Firefox and it doesn't work on IE at all.
I'm on the latest btw 1.9.1.

Cheers.

**Comment by bencripps** [comment]
Ah I see the issue. The click target has changed. If you click the farthest left point of the header, it will sort. I need to change this though. I will prioritize the issue, and get it fixed as soon as I can. Hopefully tomorrow.

**Comment by innopal** [comment]
Thanks Ben! Much appreciated.

**Comment by bencripps** [comment]
Issue has been fixed. The problem was that the bulk action toolbar plugin (which you may not want to use anyway), was covering the clickable area. Install from master and see if it works for you.

**Comment by innopal** [comment]
You're a genius Ben! It works now. I close this.

**Comment by innopal** [comment]
Forgot! Any plans for a new release?

**Comment by bencripps** [comment]
Version 1.9.2 has been published!
