### ISSUE TITLE
Feedback: demo issues

### ISSUE THREAD

**Issue by kayazinc** [bencripps/react-redux-grid#31]
First of all, slick library and good work.  Thanks.

However, the demo that you have at http://react-redux-grid.herokuapp.com does not show the vast capabilities of this component:
- Dragging Column Orderring (does not refresh).
- Sortable Columns (clicked but nothing happen).
- Delete of rows (clicked but nothing happen, not sure if this is intended).

Tested using chrome (50.0.2661.102) and firefox (47.0.1).

**Comment by bencripps** [comment]
Agreed, I've been meaning to update the demo page to include the newest feature set. I will spend some time this weekend updating the demo page, to get it current with the newest version. I'll let you know when the changes have been made.

Thanks!

**Comment by bencripps** [comment]
I've updated the demo site to include the newest version of the grid (which fixes the bugs you mentioned). Thanks for the feedback!

**Comment by kayazinc** [comment]
Thanks @bencripps, may i know which demo show the sorting capabilities.

**Comment by bencripps** [comment]
@kayazinc the complex demo now has sorting enabled.

**Comment by bencripps** [comment]
Closing this issue for now -- if you have other issues/requests, please let me know.

**Comment by kayazinc** [comment]
@bencripps, thanks for the quick response, its a beauty!
