### ISSUE TITLE
Question: source codes for the demo?

### ISSUE THREAD

**Issue by kayazinc** [bencripps/react-redux-grid#34]
@bencripps, sorry for being noob, is the source codes for the demo (http://react-redux-grid.herokuapp.com/) released?

If yes, please direct me to the download link.  Thanks!

**Comment by bencripps** [comment]
I've created a repository that has the source code for the demo app -- I'll keep this current with the app as it gets updated.

https://github.com/bencripps/react-redux-grid-demo

**Comment by kayazinc** [comment]
Thank you @bencripps.
