### ISSUE TITLE
Error: ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by kayazinc** [bencripps/react-redux-grid#38]
Does the component support server-side rendering?  I got the following errors:
```
error: ReferenceError: navigator is not defined
    at Object.<anonymous> (D:\dev\project\watchlist\node_modules\react-redux-grid\dist\components\layout\header\Column.js:31:30)
...
```

Do I need to set any environment setting?  Please advise.  Thanks.

p.s: I will google to see if there is any solution to this.

**Comment by kayazinc** [comment]
Confusing to me, is nodejs is trying to compile this library?

**Comment by bencripps** [comment]
No, currently the grid does not support server-side rendering. That's possibly a future goal, but there's no plan to implement that in the near-term. Closing this issue, but appreciate the question.
