### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by reharik** [bencripps/react-redux-grid#4]
Hi, I know this is pretty new, but I'm having a bit of trouble getting it installed in my app.
I have listed my current issues below.  If you help me get it working I can do a pull request on your docs, and incorporate what I have learned.
Thanks,
Raif

1) I'm not sure how to join it's store with my existing store.  My store set up currently looks like this:

var middlewares = [thunk, api];

    const enhancer = compose(
        // Middleware you want to use in development:
        applyMiddleware(...middlewares),
        // Required! Enable Redux DevTools with the monitors you chose
        DevTools.instrument()
    );
    const store = createStore(reducer,enhancer);

2) I created a component that looks like this:
import { Grid, Store } from 'react-redux-grid'

    const data = [
    {
        name: 'Michael Jordan',
        position: 'Shooting Guard'
    },
    {
        name: 'Charles Barkley',
        position: 'Power Forward'
    }
    ];

    const gridData = {
        store: Store,
        ...data
    };

    export default <Grid { ...gridData } />

when I try to start it I get

ERROR in ./~/react-redux-grid/src/style/main.styl
Module parse failed: /home/reharik/Development/MethodFitness/MF_FrontEnd/node_modules/react-redux-grid/src/style/main.styl Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| @import 'mixins'
| @import 'font'
| @import 'icons'
 @ ./~/react-redux-grid/src/components/Grid.jsx 58:0-29

My webpack loaders look like this: 

    { test   : /\.jsx?$/, exclude: /[\\\/]node_modules[\\\/](?!react-redux-grid)/, loader : 'babel-loader' },
            { test: /\.css$/, loader: 'style-loader!css-loader' },
            { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file" },
            //{ test: /\.(woff|woff2)$/, loader:"url?prefix=font/&limit=5000" },
            { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/octet-stream" },
            { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=image/svg+xml" },
            { test: /\.png$/, loader: "url-loader", query: { mimetype: "image/png" } },
            { test: /\.jpg$/, loader: "url-loader", query: { mimetype: "image/jpg" } },
            { test: /\.gif$/, loader: "url-loader", query: { mimetype: "image/gif" } },
            {
                test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loaders: ['url-loader?limit=10000&mimetype=application/font-woff' ]
            },
            { test: /\.styl$/, exclude: /node_modules|\.json$/, loaders: ['style-loader', 'css-loader', 'stylus-loader'] }

**Comment by bencripps** [comment]
You will need to update your loaders, specifically for stylus -- you're excluding `node_modules`:

```
var loaders = [
    {
        test: /\.js$|\.jsx$/,
        loaders: ['react-hot', 'babel-loader'],
        exclude: /[\\\/]node_modules[\\\/](?!react-redux-grid)/,
    },
    {
        test: /\.styl$/,
        exclude: /[\\\/]node_modules[\\\/](?!react-redux-grid)/,
        loaders: ['style-loader', 'css-loader', 'stylus-loader']
    }
]
```;

Let me know if this doesn't fix the issue.

As far as using your own store, you should simply pass your store (and your store generation looks good), to the Grid. You will also need to hook up the grid reducers to your own store. (Take a look at the docs for this).

**Comment by reharik** [comment]
Hey, It looks like I have those two loaders, the only difference is that the .js$ doesn't have the react-hot which I presume is not a requirement.  So in my list of loaders above, they are the first and the last loaders.
R

**Comment by bencripps** [comment]
In order for webpack to compile the grid styles, the `stylus-loader` needs to be able to access the files.

Yes, you have the stylus loader listed, But take a look:

` { test: /\.styl$/, exclude: /node_modules|\.json$/, loaders: ['style-loader', 'css-loader', 'stylus-loader'] }`

Your `exclude` parameter declares that webpack should not build any files in the `node_modules` folder, which is where the grid is installed. Change the `exclude` pattern to this:

`exclude: /[\\\/]node_modules[\\\/](?!react-redux-grid)/`

**Comment by bencripps** [comment]
@reharik did this fix your issue? Were you able to get your store hooked up?

**Comment by reharik** [comment]
sorry, I have not had a chance to get to it.  I will hopefully get it
tonight.  Thanks,
R

**Comment by reharik** [comment]
Hi, just had a moment to try your fixes.  It looks like things have gotten
better for sure.  However, I am now getting this error

*ERROR in Cannot find module 'stylus'*
* @ ./~/react-redux-grid/src/style/main.styl 4:14-103 13:2-17:4 14:20-109*

The file does seem to be there. although I'm not sure about those path
tokens (./~/).  If those mean "in my node_modules folder" than the file is
there. :)
I wish I understood webpack a bit better so I could debug this myself, but
I just have not had the time to dig in.  It's on my list though.
Thanks,
Raif

**Comment by bencripps** [comment]
`npm install stylus` will fix this but make sure you npm installed the grid correctly as well. I might clean your `node_modules` folder and rerun `npm install`

**Comment by reharik** [comment]
Indeed, I had stylus-loader, but not stylus it's self.
I have a new error, but it's not this issue, and probably my fault, so I
will close this issue,
Thank you for your help.
Raif
