### ISSUE TITLE
Custom sorting

### ISSUE THREAD

**Issue by innopal** [bencripps/react-redux-grid#41]
I can't figure out a way to add a custom sorting function to a column. Is it possible?

**Comment by bencripps** [comment]
Do you want a custom `remote` sort or a custom `local` sort?

**Comment by innopal** [comment]
Sorry I didn't clarify! Just local sort. For example I have date columns I need to sort asc and desc.

**Comment by bencripps** [comment]
No this feature hasn't been implemented yet. I'll keep this issue open and get to it as soon as I can.

**Comment by innopal** [comment]
Thanks for adding the feature to your backlog.

Any workaround you can think of in the meantime? Any event that can intercept sorting a column (with proper payload incl. column and sort direction)?

Cheers.

**Comment by bencripps** [comment]
Each header definition has the event `HANDLE_CLICK`;

on the fire of this event, you could simply use the `Actions.GridActions.setData` method to set the grid data with the newly sorted data. Just a thought.

**Comment by bencripps** [comment]
@innopal so does the default local sorting that comes by default doesn't work for you, since these are dates, is that correct?

**Comment by innopal** [comment]
Yeah primarily, if the data is date type it doesn't sort correctly. I need to be able to add my own sorting like:

`mylist.sort((a, b) => (moment(a) - moment(b))) `

**Comment by bencripps** [comment]
ok cool, this should be fairly simple to implement. it should be done and pushed within the next couple days.

**Comment by bencripps** [comment]
This is done.

On the column you'd like to be able to custom sort, you will need to add the following:

````js
const columns = [
    {
        name: 'Column with custom Sort',
        dataIndex: 'sortable',
        sortable: true
        sortFn: (a, b) => {
            // your sort logic
        }
    },
    // ... rest of columns
];
````

**Comment by innopal** [comment]
Thanks @bencripps,
It doesn't work though! It doesn't fire sortFn at all.

Cheers.

**Comment by bencripps** [comment]
Hmm, I wrote a test around it, and I just ran the tests/ ran through it in a browser and it seems to work. If you put a debugger in the sortFn, it doesn't get called?

**Comment by innopal** [comment]
Nope! it doesn't.

**Comment by bencripps** [comment]
on the column, is `sortable: true` set?

**Comment by bencripps** [comment]
@innopal let me know if that fixed your issue, otherwise could you send me the column definition?

**Comment by bencripps** [comment]
@innopal i'd like to get this issue closed, lemme know if you still have issues -- otherwise I will close soon.

**Comment by innopal** [comment]
Hi Ben,
Sorry I was MIA for a while.
As I mentioned I never managed to get sortFn to fire. And yes, sortable is true.
I'm getting all sorts of error now. Any ideas what's happening here?
Here are some warnings and error I get back to back:
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Row`. See https://fb.me/react-warning-keys for more information.
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `EmptyCell`.
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `EmptyCell`.

**Comment by bencripps** [comment]
Hmm, that's a whole bunch of errors -- I also can't reproduce the `sortFn` not firing. Could you find the simplest version of your grid implementation and send it to me? I can debug it from there, and see whats going on.

**Comment by innopal** [comment]
Hi @bencripps,

Now I can get the sortFn to work, so thanks for the feature.
However, it doesn't have a direction (asc/desc) parameter, hence, toggling doesn't work and it always sorts one way.


Any ideas?

**Comment by bencripps** [comment]
That's a good point, I will pass the direction into the function. I'll push a commit to master and you can test.

**Comment by bencripps** [comment]
Should work now -- direction will be the first argument, and will either be `DESC` OR `ASC`. Here's an example of how this could work.

````js
const sortFn = (direction, prev, curr) => {
    if (direction === 'DESC') {
        return prev - curr;
    }
    return curr - prev;
};
````

**Comment by innopal** [comment]
@bencripps, master branch works great! Any release plans?

**Comment by bencripps** [comment]
released as  2.2.6

**Comment by innopal** [comment]
Hey Ben @bencripps,

Did you just camelCased all the reducers in 2.3.0?

**Comment by bencripps** [comment]
Instead of importing your reducers like: 

````js
import { Reducers } from 'react-redux-grid';

const gridReducers = {
  dataSource: Reducers.DataSource,
  editor: Reducers.Editor,
  errorHandler: Reducers.ErrorHandler,
  filter: Reducers.Filter,
  grid: Reducers.grid,
  loader: Reducers.Loader,
  menu: Reducers.Menu,
  pager: Reducers.Pager,
  selection: Reducers.Selection,
};

export default combineReducers({
  facility,
  language,
  routing,
  form,
  ..gridReducers,
});
````

you will simply do this:

````js
import { Reducers as gridReducers } from 'react-redux-grid';

export default combineReducers({
  facility,
  language,
  routing,
  form,
  ..gridReducers,
});
````

**Comment by innopal** [comment]
@bencripps 
Hi Ben,

I'm trying to keep the last state that grid was sorted on in my redux store.
Something like:
```
{
  dataIndex: 'name',
  direction: 'DESC'
}
```
Is there any event that I can intercept to record that state each time, a sort is fired?

Cheers

**Comment by bencripps** [comment]
hey @innopal, could you create new issues for these? Since this is a closed issue, and you're addressing other features/bugs, it's probably best to open as another issue. Thanks!
