### ISSUE TITLE
Typo in createFromKey

### ISSUE THREAD

**Issue by innopal** [bencripps/react-redux-grid#45]
Hi Ben,

In documentation it says createKeyFrom and in the detailed doc it says createFromKey!

Which one is correct?

**Comment by bencripps** [comment]
Sorry about that, `createKeyFrom` is the right one.

**Comment by innopal** [comment]
I use createKeyFrom for my primary key column but I am getting this warning:
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Row`. See https://fb.me/react-warning-keys for more information.

It seems like it deosn't translate that to setting a key for the row and the key is null and react doesn't like it.

Any ideas?

PS: that warning is followed by this:
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `EmptyCell`.

...and then there is this error:

Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `EmptyCell`.

I suspect these are all related.

I am populating the grid with correct data fyi (it has 8 rows), but it doesn't render the rows in the grid.

**Comment by bencripps** [comment]
You shouldn't be using `createKeyFrom` unless the values will be defined, and unique. This will cause all kinds of issues in the React internals if the keys are duplicates or undefined. I would simply not specify this parameter.

**Comment by innopal** [comment]
Apparently my warnings and errors are unrelated to createFromKey. I get those even when I remove that setting.

Any ideas why it is asking for unique key prop when rendering the Row?

**Comment by bencripps** [comment]
Can you attach here, your 8 rows (the objects describing the data in each row), and the column definitions? I can spin up a grid and see what happens.

**Comment by innopal** [comment]
Thanks for your offer Ben. It's not the rows, it happens even when there is one. 
I have to do more debugging and figure this out.
Regardless, I will close this. Since you fixed the docs.
Cheers
