### ISSUE TITLE
columns prop of Row

### ISSUE THREAD

**Issue by innopal** [bencripps/react-redux-grid#47]
Hi Ben,

I have this weird experience that the grid is not rendering data.
It seems like the columns prop of the Row is an empty array but columns prop of columnManager prop of the Row has all the 5 columns. Why the columns is empty?

Any ideas?

**Comment by bencripps** [comment]
A similar issue has been reported (I believe it's a bug in the new stateful feature). I'm researching this morning, and will have a fix soon.

**Comment by bencripps** [comment]
@innopal this was causing a different but possibly related issue. Would you mind installing master and seeing if that fixes your issue?

**Comment by innopal** [comment]
@bencripps It did not fix my issue. I still see the columns array empty (in Row.js) but columns property in columnManager has all the columns. Funny thing is that I don't even have column manager as a plugin. In fact my plugins array is empty.

**Comment by bencripps** [comment]
Could you post all of the data you are passing the grid? Columns, a sample of 5 or so rows, and all the other config your passing.

**Comment by innopal** [comment]
Sure.
Here is the config:
const config = {
      columns,
      pageSize,
      plugins,
      events,
      height,
      stateKey: gridStateKey,
      store: this.context.store,
    };

Here is the render:
return (
      <div className="content container">
      <Grid {...config} data={this.props.appointments} />
      </div>
    );

And here is the configuration:
export const pageSize = 20;
export const gridStateKey = 'appointments-grid-stateKey';

export const height = '';

export const events = {
  HANDLE_ROW_CLICK: () => {},
};

export const plugins = {};

export const columns = [
{
    name: 'Date',
    dataIndex: 'date',
    sortable: true,
    width: '20%'
},
{
    name: 'Name',
    dataIndex: 'name',
    sortable: true,
    width: '20%'
}
];

Oh and Data:
[{ date: '2016/08/28', name: 'John Doe'}]

**Comment by bencripps** [comment]
It doesn't look like you're passing the `data` object to the `config`? Perhaps you are and you missed it here?

**Comment by innopal** [comment]
yes I do. Github ate my code:) I forgot to wrap it in code tag!

Here it is:
Here is the render:
```
return (
     <div className="content container">
        <Grid {...config} data={this.props.appointments} />
     </div>
);
```

**Comment by bencripps** [comment]
![image](https://cloud.githubusercontent.com/assets/6272507/17944591/0fcce7e8-6a06-11e6-8ef7-2c124258cadd.png)

I've loaded that exact config into the demo page, and it seems to load. Do you have an errors in the console?

**Comment by bencripps** [comment]
The only thing I can think is that you've incorrectly imported all the grid reducers, could you paste where you're creating your `rootReducer`?

**Comment by innopal** [comment]
```
import { Reducers } from 'react-redux-grid';
const gridReducers = {
  dataSource: Reducers.DataSource,
  editor: Reducers.Editor,
  errorHandler: Reducers.ErrorHandler,
  filter: Reducers.Filter,
  grid: Reducers.grid,
  loader: Reducers.Loader,
  menu: Reducers.Menu,
  pager: Reducers.Pager,
  selection: Reducers.Selection,
};
export default combineReducers({
  facility,
  language,
  routing,
  form,
  ..gridReducers,
});
```

**Comment by bencripps** [comment]
Ah, you've got a typo there. 

`grid: Reducers.grid` should be  `grid: Reducers.Grid`

Try that out and let me know?

**Comment by innopal** [comment]
Good eyes!

Thanks mate.
