### ISSUE TITLE
Theming with bootstrap, etc.

### ISSUE THREAD

**Issue by innopal** [bencripps/react-redux-grid#51]
Hi Ben,

Is there a way to theme the grid with particular css frameworks.
Let's say for example: Theme it with bootstrap and associate the grid with bootstrap css classes like:
_**table, table-bordered, table-hover, table-responsive**_, etc.. so that when my bootstrap theme changes, the grid's look and feel changes as well.

That would be really nice.

Cheers

**Comment by innopal** [comment]
@bencripps,

I looked at the documentation and I am suspecting that I might be able to do this just by overriding CSS_PREFIX and ClassNames properties of the grid.

But when I tried it, it seems like it ignores the overrides.
So the question is can I override both css prefis and classnames properties?
And if yes how exactly you do it?

I tried:
```
const cssPrefix = 'table';
const classNames = { 
  ROW: 'row',
  ... // Rest of the names go here.
}
const config = {
  cssPrefix,
  classNames,
  ... // Rest of the grid config
}

return (
  <Grid {...config} />
)
```

but it seems like it is ignoring both cssPrefix and classNames!

Any advice?

Cheers

**Comment by bencripps** [comment]
This is the intended design. All of the CSS classes are defined in the dictionary, and the CSS prefix is defined as a core constant. 

The implementation has not been complete, which allows these variables to be configurable. We're currently working on drag and drop, and a couple other high priority bugs. Once these have been complete, I will finish up this enhancement.

**Comment by innopal** [comment]
Thanks @bencripps,

Looking forward to it.

Cheers

**Comment by innopal** [comment]
Any news on this @bencripps ?

**Comment by bencripps** [comment]
@innopal working on it now! i'll let you know as soon as its ready.

**Comment by bencripps** [comment]
ok @innopal clone down master. you will need to run `npm run dist` in order to get the built assets (since this is no longer a part of the source control). let me know if you have any issues, otherwise I can make a new release.

**Comment by innopal** [comment]
Thanks @bencripps ,

This is a game changer man! I'll play with it and get back to you asap.

Cheers

**Comment by innopal** [comment]
Very close Ben!

I found a couple of issues:
1. When you set the prefix to an empty string, it adds a hyphen to the beginning of all classes. 
like -container.
2. Some class names seem to be used as a selector in your code so you cannot set them to empty, for example ROW. This is not a huge issue but needs to be documented.

It would also be nice to document a mapping of these classnames to popular css frameworks, For example a rough mapping for Bootstrap would be:

```
applyGridConfig({
    CLASS_NAMES: {
        TABLE: 'table table-sriped',
        TABLE_CONTAINER: 'table-responsive',
        CONTAINER: 'container',
        HEADER: 'header',
        ROW: 'row',
        CELL: 'cell',
        COLUMN: 'column'
    },
    CSS_PREFIX: ''
});
```

Cheers

**Comment by bencripps** [comment]
Awesome! I will take a look at these bugs this morning.

**Comment by bencripps** [comment]
@innopal I've fixed the CSS_PREFIX issue so that if you set CSS_PREFIX to false or '' it will not add the dash delimiter. 

I also checked the rest of the source code for any reference to a 'react-grid' string literal, and I don't see anything that should be causing issues. Can you let me know more speficially what issues you're seeing with row?

Since you're working on getting the bootstrap example mapped, would you mind posting it in this issue thread so that others can use it when you've got it working?

**Comment by bencripps** [comment]
one other note -- I set the row class to empty string, and that does create an error. But I think that's ok. If you don't want the default grid css, just change the row class to something else, that wont inherit any css.

**Comment by pgoldweic** [comment]
Would you mind posting instructions on how to use this new feature? I'd also like to use Bootstrap styles with this grid (and I'm a react/redux newbie). Thanks!

**Comment by innopal** [comment]
Hi @bencripps ,

Sorry I've been swamped these days.
I got the latest and it works, so feel free to kick off a release.

For your users I you like to use bootstrap styling I;d just say:

Instead of the usage example in the document:

```
import { Grid, Store } from 'react-redux-grid'

const config = {
    store: Store,
    stateKey: 'unique-grid-id',
    ...data
};

const GridInstance = <Grid { ...config } />
```

Try this instead:
```

import { Grid, Store, applyGridConfig } from 'react-redux-grid'

const config = {
    store: Store,
    stateKey: 'unique-grid-id',
    ...data
};

applyGridConfig({
    CLASS_NAMES: {
        TABLE: 'table table-striped',
        TABLE_CONTAINER: 'table-responsive',
        HEADER_FIXED_CONTAINER: 'hidden',
        HEADER: 'header-bs',
        ROW: 'row-bs',
        CELL: 'text-left',
        COLUMN: 'column-bs',
    },
    CSS_PREFIX: '',
});

const GridInstance = <Grid { ...config } />
```


Cheers,

**Comment by bencripps** [comment]
The only thing I would add would be to hide the error_container. The file config would be:

````js
applyGridConfig({
    CLASS_NAMES: {
        TABLE: 'table table-striped',
        TABLE_CONTAINER: 'table-responsive',
        HEADER_FIXED_CONTAINER: 'hidden',
        HEADER: 'header-bs',
        ROW: 'row-bs',
        CELL: 'text-left',
        COLUMN: 'column-bs',
        ERROR_HANDLER: {
            CONTAINER: 'hidden'
        }
    },
    CSS_PREFIX: ''
});
````

**Comment by pgoldweic** [comment]
Thanks!

**Comment by bencripps** [comment]
I've added a bootstrap example to the demo page.

http://react-redux-grid.herokuapp.com/

The source is available here;

https://github.com/bencripps/react-redux-grid-demo/blob/master/app/public/dev/scripts/src/components/app/grid-container/Bootstrap.js
