### ISSUE TITLE
Question: Drag and Drop row to non-grid item

### ISSUE THREAD

**Issue by jktravis** [bencripps/react-redux-grid#59]
Hi again.

Is there a configuration item which would allow one to drag a whole row (plus/minus children) to a non-grid item? Like a separate `<div/>` somewhere?

**Comment by bencripps** [comment]
Since the Grid won't own the piece of DOM that will receive the drop event I'm not sure what the Grid can do here, aside from associating some metadata with the dragged element. 

What would the desired behavior be?

**Comment by jktravis** [comment]
I think so. I'd ultimately like to be able to drag a row both in and out of the grid from/to some custom widget. I think as long as I'm able to identify which row it was on either end, I can fetch the item from my store in my own reducer (at least from Grid to Custom.) Not sure exactly how to do it the other way. 

I've been debating on trying to write my own for a while now so I can do this kind of thing. It just seems like so much work to not leverage something like your project, though.

**Comment by bencripps** [comment]
What I would recommend is creating a `drop` event on some container and having the event trigger some actions.

I've just push a commit which adds some metadata to the drop event so you will know which row has been dropped. Here's a sample drop event that will remove the row from the grid. 

````js
import { Actions } from 'react-redux-grid';
import { store } from './path/to/store';
import { stateKey } from './path/to/constants';

const dropEvent = (e) => {
    // get data from drop event
    const { id, row } = e.dataTransfer.gerData('text/plain');
    
    // get grid data from store
    const gridData = store
        .getState()
        .dataSource.getIn([stateKey, 'data'])
    const index = gridData.findIndex(i => i.id === id);

    // remove row from grid using action
    store.dispatch(
        Actions.EditorActions.removeRow({
            stateKey,
            index
        })
    );

    //custom code to add row to another area

    // Actions.addNewRow is also available if you'd
    // like to add a row

};
````

As far as dropping a new into grid, that's a little more complex. We could expose a `rowDrop` event that get's passed through with props, and you could simply write your own event that handles this by firing custom or grid actions?

**Comment by jktravis** [comment]
Thanks, so much! 

I think an event that would accept the row to add/update would be helpful. How would this affect the other DnD row functions for reordering? Would those still work the same?

**Comment by bencripps** [comment]
Yeah I think those would work the same. I don't think we could support hinting on the drop of a custom element on a row, since the Grid won't be aware of what's being dropped.

**Comment by bencripps** [comment]
@jktravis closing this issue. If you'd like a row drop event, would you mind opening up a new issue, requesting the feature?
