### ISSUE TITLE
Cell Content

### ISSUE THREAD

**Issue by reharik** [bencripps/react-redux-grid#7]
Hi, maybe this is a real issue not something I'll find the answer to in 5 minutes :)
Is there a way to specify the contents of a cell, meaning the html contents? Can we put a component in there so as to display an image, or just a link?
Thanks,
R

**Comment by bencripps** [comment]
Yes, this is possible. I've update the docs to be more clear, but here is an example of a column renderer, which is what you're looking for:

```
const columns = [
     {
         name: 'Image',
         dataIndex: 'id',
         renderer: Image,
         editable: false
     }, ...
]

export const Image = ({ column, value, row }) => {
    return (
        <img src= { value } />
        );
};
`

**Comment by reharik** [comment]
Excellent, Thank you, and the docs are better.  I had seen reneder but thought it was just for, or, well, not sure what I thought it was for.  But I know now!
Thanks,
Raif
