### ISSUE TITLE
npm run demo fails to work properly

### ISSUE THREAD

**Issue by jstafford** [bencripps/react-redux-grid#88]
Steps to reproduce:
1. Make a local clone of the react-redux-grid: 
```bash
$ git clone https://github.com/bencripps/react-redux-grid.git
$ cd react-redux-grid
```
2. Follow the steps in the "Installation" section of README.MD to build and run the demo:
```bash
$ npm install
$ npm run demo
```
3. Open your browser pointed to [http://localhost:8080](http://localhost:8080)

Observed behavior:
* A blank page loads in the browser, and the following error is displayed in the terminal, `"GET /demo/lib/bundle.js" Error (404): "Not found"`

Expected behavior:
* The grid displays in the browser, and there is no error.

Note: I have a simple fix for this issue and will be submitting it immediately.

**Comment by algbeta** [comment]
Hey guys!
Is the fix merged already?
Demo still fails for me.

**Comment by bencripps** [comment]
This has been fixed atleast for my workflow. First off, the demo won't load unless you also have the `hot-reloader` also loading, which is triggered by `npm run hot`

```bash
$ npm run demo:run
$ npm run hot
```

And you should have it work -- @jstafford let me know if there is another way you envisioned this working?

**Comment by jstafford** [comment]
@bencripps What do you think about adding a new script called "start" that starts both hot and demo, like people might be used to with a create-react-app based project? Then changing the readme to suggest that if they want to play with it, that they just do npm install, npm run start? Certainly the readme is misleading as it is currently written. When I put my fix in, I wasn't even thinking about hot reloading, I was just trying to make it work as the instructions were written in the readme. It makes a lot more sense to have hot reloading, so I see why you backed out my change to the path to bundle.js.  I'm going to make a pull request and you can give me some feedback if you want to change it around a little.
