### ISSUE TITLE
Question: validation on cell being edited

### ISSUE THREAD

**Issue by algbeta** [bencripps/react-redux-grid#96]
Hi!

I'm using a grid editor with `type = 'grid'` and `validator` function for email cells.
While debugging I can see that my `validator` function is called and returns proper value for invalid cells, however even it returns false I can not see any action happening with grid/cell/row.

So here is the question:
Is anything supposed to happen? should the invalid row have additional class (smth like .invalid or .error)?

Thank you very much!

**Comment by bencripps** [comment]
Hey, thanks for posting this issue! 

At this point :(, the validator only works with the `inline` edit mode -- which adds a class, and disables the save button so the current row cannot be saved. I think this would be a valuable feature to add -- how would you like to see this work?

Please detail how you would like the `validator` function to affect the grid when it is in `grid` mode -- I will mark this one as **help wanted** just in case anyone wants to pick this one up, but I think this would be a nice feature to add, so I can hop on this one soon.

**Comment by algbeta** [comment]
Hi again!
I believe that in case of grid edit mode it's enough to add additional classes to invalid row and/or cell.
It's okay to save invalid data and let a developer care how he'd like to handle data from invalid rows.
In that case it will be also useful to have access to invalid row's data

What do you think?
Thanks!

**Comment by bencripps** [comment]
I've pushed some new code (that will be released with this week's patch). I've added support for both editModes (grid, and inline) which will add a class to any cell that is currently while being edited.

As far as for eventing -- the `values` of the row being saved (in inline mode) are part of the arguments passed to `HANDLE_BEFORE_INLINE_EDITOR_SAVE` and `HANDLE_AFTER_INLINE_EDITOR_SAVE` so you can handle the logic around that yourself. 

For grid editmode, I'm still thinking about how we can trigger a couple events. When those events are created, the row `values` will also be included in the arguments for those callbacks.

**Comment by bencripps** [comment]
Published in [5.1.9](https://github.com/bencripps/react-redux-grid/releases/tag/5.1.9)
