### ISSUE TITLE
Styling problem: no down arrow is shown when change sorting order

### ISSUE THREAD

**Issue by algbeta** [bencripps/react-redux-grid#97]
Hi!

This problem can be reproduced on demo site too
http://react-redux-grid.herokuapp.com/Simple

when you change column sorting to asc sorting arrow in the column header disappears however i can see it among styles
`.react-grid-header th .react-grid-sort-handle.react-grid-asc::before`
but it's not being caught

Hope it helps!
Thank you!

**Comment by bencripps** [comment]
Thanks for posting this issue -- this was the result of a style refactor done a few weeks ago. Sorry about that.

The bug has been fixed, you can clone down master from github and verify the changes work for you as well. Make sure to run `npm run dist` to ensure you've built the latest code.

Let me know if this resolves the issue, and I will create a new release.

**Comment by algbeta** [comment]
Hi,
Looks like it's fixed!
Thanks!

**Comment by bencripps** [comment]
Published in [5.1.9](https://github.com/bencripps/react-redux-grid/releases/tag/5.1.9)
