### ISSUE TITLE
editor in mode=inline and key events

### ISSUE THREAD

**Issue by algbeta** [bencripps/react-redux-grid#99]
Hi again!
I have another question.

When i use editor plugin in mode=inline I would really like 'Save' and 'Cancel' to be responsive to key events. I think it's a good idea to save on pressing Enter and cancel on pressing Escape or allow to set up your own shortcut for save/cancel.

I investigated this issue a bit and the easiest solution for non-input components seems to be adding keyup listeners on componentDidMount and removing those listeners  on componentWillUnmount in Inline or Button component.

What do you think?
Thanks!

**Comment by bencripps** [comment]
I think that could work! And I think your solution has merit -- if you'd like open a PR with these changes, that would be awesome!

**Comment by bencripps** [comment]
Actually, I've got this one implemented mostly. Just updating tests. I'll push once it's done.

**Comment by bencripps** [comment]
Ok the change has been pushed -- clone down master and see if this works for you! :)

**Comment by algbeta** [comment]
Hi!
I've checked demo and keyboard events are present and work nicely!
Thanks!

**Comment by bencripps** [comment]
No problem, this will get published with this weeks release!

**Comment by bencripps** [comment]
Published in [5.1.9](https://github.com/bencripps/react-redux-grid/releases/tag/5.1.9)
